export type SHOPFILTERSTYPE = {
  [key: string]: {
    gender: string[];
    sport: string[];
    brand: string[];
    colors: string[];
    sizes: string[];
  };
};
export type FilterKeys = "gender" | "sport" | "brand" | "sizes" | "colors";

export const SHOP_FILTERS: SHOPFILTERSTYPE = {
  // COLLECTIONS
  featured: {
    gender: ["women", "men"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "columbia",
      "inov",
      "la sportiva",
      "new balance",
      "nike",
      "ocun",
      "on",
      "red chili",
      "salomon",
      "scarpa",
      "tenaya",
      "under armour",
    ],
    // bagde: ["featured"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  new: {
    gender: ["women", "men"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "columbia",
      "inov",
      "la sportiva",
      "new balance",
      "nike",
      "ocun",
      "salomon",
      "saucony",
      "scarpa",
      "tenaya",
      "under armour",
    ],
    // bagde: ["new"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  sale: {
    gender: ["women", "men"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "la sportiva",
      "new balance",
      "nike",
      "on",
      "red chili",
      "salomon",
      "saucony",
      "scarpa",
      "under armour",
    ],
    // bagde: ["sale"],
    sizes: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  // CATEGORY
  running: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "inov",
      "new balance",
      "nike",
      "on",
      "saucony",
      "under armour",
    ],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  runningfeatured: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: ["adidas", "altra", "asics", "brooks", "new balance", "nike", "on"],
    // bagde: ["featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  runningnew: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: [
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "saucony",
      "under armour",
    ],
    // bagde: ["new"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "pink",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  runningsale: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: ["adidas", "altra", "asics", "brooks", "nike", "on", "saucony"],
    // bagde: ["sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  training: {
    gender: ["men", "women"],
    sport: ["training"],
    brand: ["adidas", "inov", "new balance", "nike", "under armour"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  "cross trainingfeatured": {
    gender: ["men", "women"],
    sport: ["training"],
    brand: ["inov", "new balance", "nike", "under armour"],
    // bagde: ["featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "red",
      "teal",
    ],
  },
  "cross trainingnew": {
    gender: ["men", "women"],
    sport: ["training"],
    brand: ["new balance", "nike", "under armour"],
    // bagde: ["new"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: ["beige", "black", "darkblue", "grey", "red", "slateblue", "white"],
  },
  "cross trainingsale": {
    gender: ["women", "men"],
    sport: ["training"],
    brand: ["adidas", "new balance", "nike", "under armour"],
    // bagde: ["sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: ["black", "darkblue", "grey", "red", "teal", "white"],
  },
  hiking: {
    gender: ["women", "men"],
    sport: ["hiking"],
    brand: [
      "adidas",
      "altra",
      "brooks",
      "columbia",
      "inov",
      "new balance",
      "nike",
      "salomon",
    ],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "14.5",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "teal",
      "white",
    ],
  },
  hikingfeatured: {
    gender: ["women", "men"],
    sport: ["hiking"],
    brand: ["altra", "brooks", "columbia", "new balance", "nike", "salomon"],
    // bagde: ["featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "sienna",
      "teal",
      "white",
    ],
  },
  hikingnew: {
    gender: ["women", "men"],
    sport: ["hiking"],
    brand: ["altra", "brooks", "columbia", "inov", "new balance", "salomon"],
    // bagde: ["new"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "orange",
      "red",
      "sienna",
      "teal",
    ],
  },
  hikingsale: {
    gender: ["women", "men"],
    sport: ["hiking"],
    brand: ["adidas", "new balance", "salomon"],
    // bagde: ["sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: ["darkblue", "lightblue", "orange"],
  },
  climbing: {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: [
      "black diamond",
      "la sportiva",
      "ocun",
      "red chili",
      "scarpa",
      "tenaya",
    ],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "pink",
      "red",
      "sienna",
      "teal",
      "white",
      "yellow",
    ],
  },
  climbingfeatured: {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: [
      "black diamond",
      "la sportiva",
      "ocun",
      "red chili",
      "scarpa",
      "tenaya",
    ],
    // bagde: ["featured"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: [
      "black",
      "blue",
      "grey",
      "lightblue",
      "orange",
      "red",
      "teal",
      "white",
    ],
  },
  climbingnew: {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["black diamond", "la sportiva", "ocun", "scarpa", "tenaya"],
    // bagde: ["new"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: [
      "black",
      "blue",
      "green",
      "pink",
      "red",
      "sienna",
      "teal",
      "yellow",
    ],
  },
  climbingsale: {
    gender: ["women", "men"],
    sport: ["climbing"],
    brand: ["black diamond", "la sportiva", "red chili", "scarpa"],
    // bagde: ["sale"],
    sizes: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11.5",
    ],
    colors: ["black", "blue", "red", "teal", "yellow"],
  },
  //   MEN
  men: {
    gender: ["men"],
    sport: ["running", "training", "hiking", "climbing"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "columbia",
      "inov",
      "la sportiva",
      "new balance",
      "nike",
      "ocun",
      "on",
      "red chili",
      "salomon",
      "saucony",
      "scarpa",
      "tenaya",
      "under armour",
    ],
    // badge: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "14.5",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  //   MEN CATEGORY
  menrunning: {
    gender: ["men"],
    sport: ["running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "inov",
      "new balance",
      "nike",
      "on",
      "saucony",
      "under armour",
    ],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  "mencross training": {
    gender: ["men"],
    sport: ["training"],
    brand: ["adidas", "inov", "new balance", "nike", "under armour"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "red",
      "sienna",
      "teal",
      "white",
    ],
  },
  menhiking: {
    gender: ["men"],
    sport: ["hiking"],
    brand: ["adidas", "altra", "brooks", "columbia", "inov", "nike", "salomon"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "14.5",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "teal",
      "white",
    ],
  },
  menclimbing: {
    gender: ["men"],
    sport: ["climbing"],
    brand: [
      "black diamond",
      "la sportiva",
      "ocun",
      "red chili",
      "scarpa",
      "tenaya",
    ],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
    ],
    colors: [
      "black",
      "blue",
      "green",
      "grey",
      "orange",
      "red",
      "teal",
      "white",
      "yellow",
    ],
  },
  //   MEN COLLECTION
  menfeatured: {
    gender: ["men"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "columbia",
      "inov",
      "la sportiva",
      "new balance",
      "nike",
      "ocun",
      "red chili",
      "salomon",
      "scarpa",
      "tenaya",
      "under armour",
    ],
    // bagde: ["featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "teal",
      "white",
    ],
  },
  mennew: {
    gender: ["men"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "altra",
      "asics",
      "brooks",
      "columbia",
      "inov",
      "la sportiva",
      "new balance",
      "nike",
      "salomon",
      "saucony",
      "scarpa",
      "under armour",
    ],
    // bagde: ["new"],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  mensale: {
    gender: ["men"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "new balance",
      "nike",
      "on",
      "red chili",
      "saucony",
      "under armour",
    ],
    // bagde: ["sale"],
    sizes: [
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "teal",
      "white",
      "yellow",
    ],
  },
  // MEN BRAND
  menadidas: {
    gender: ["men"],
    sport: ["training", "hiking", "running"],
    brand: ["adidas"],
    // bagde: ["featured", "sale"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "14.5",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "white",
    ],
  },
  menaltra: {
    gender: ["men"],
    sport: ["hiking", "running"],
    brand: ["altra"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: ["black", "darkblue", "grey", "teal"],
  },
  menasics: {
    gender: ["men"],
    sport: ["running"],
    brand: ["asics"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  "menblack diamond": {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["black diamond"],
    // bagde: ["featured", "sale"],
    sizes: ["7", "8", "11.5", "12", "13.5", "14"],
    colors: ["blue", "grey", "white", "yellow"],
  },
  menbrooks: {
    gender: ["men"],
    sport: ["hiking", "running"],
    brand: ["brooks"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "sienna",
      "teal",
      "white",
    ],
  },
  mencolumbia: {
    gender: ["men"],
    sport: ["hiking"],
    brand: ["columbia"],
    // bagde: ["featured", "new"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
      "14",
      "15",
    ],
    colors: ["beige", "black", "green", "grey", "white"],
  },
  meninov: {
    gender: ["men"],
    sport: ["training", "hiking", "running"],
    brand: ["inov"],
    // bagde: ["featured", "new"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: ["grey", "red", "teal"],
  },
  "menla sportiva": {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["la sportiva"],
    // bagde: ["featured", "new"],
    sizes: [
      "6",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: ["black", "blue", "green", "grey", "white", "yellow"],
  },
  "mennew balance": {
    gender: ["men"],
    sport: ["training", "running"],
    brand: ["new balance"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: ["black", "grey", "red", "white"],
  },
  mennike: {
    gender: ["men"],
    sport: ["training", "hiking", "running"],
    brand: ["nike"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "teal",
      "white",
    ],
  },
  menocun: {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["ocun"],
    // bagde: ["featured"],
    sizes: [
      "6",
      "6.5",
      "7",
      "8",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: ["black", "teal"],
  },
  menon: {
    gender: ["men"],
    sport: ["running"],
    brand: ["on"],
    // bagde: ["sale"],
    sizes: [
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: ["black", "blue", "lightblue"],
  },
  "menred chili": {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["red chili"],
    // bagde: ["featured", "sale"],
    sizes: [
      "5.5",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: ["black", "blue", "red", "white"],
  },
  mensalomon: {
    gender: ["men"],
    sport: ["hiking"],
    brand: ["salomon"],
    // bagde: ["featured", "new"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: ["black", "blue", "darkblue", "lightblue", "red", "sienna", "teal"],
  },
  mensaucony: {
    gender: ["men"],
    sport: ["running"],
    brand: ["saucony"],
    // bagde: ["new", "sale"],
    sizes: [
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    colors: ["black", "blue", "grey", "white"],
  },
  menscarpa: {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["scarpa"],
    // bagde: ["featured", "new"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "orange", "white", "yellow"],
  },
  mentenaya: {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["tenaya"],
    // bagde: ["featured"],
    sizes: ["8"],
    colors: ["blue"],
  },
  "menunder armour": {
    gender: ["men"],
    sport: ["training", "running"],
    brand: ["under armour"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  // WOMEN
  women: {
    gender: ["women"],
    sport: ["running", "training", "hiking", "climbing"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "columbia",
      "inov",
      "la sportiva",
      "new balance",
      "nike",
      "ocun",
      "on",
      "red chili",
      "salomon",
      "saucony",
      "scarpa",
      "tenaya",
      "under armour",
    ],
    // badge: ["featured", "new", "sale"],
    sizes: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  //   category
  womenrunning: {
    gender: ["women"],
    sport: ["running"],
    brand: [
      "altra",
      "asics",
      "brooks",
      "inov",
      "new balance",
      "nike",
      "on",
      "saucony",
      "under armour",
    ],
    // badge: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "pink",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  "womencross training": {
    gender: ["women"],
    sport: ["training"],
    brand: ["adidas", "inov", "new balance", "nike", "under armour"],
    // "badge": [
    //     "featured",
    //     "new",
    //     "sale",
    // ],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  womenhiking: {
    gender: ["women"],
    sport: ["hiking"],
    brand: ["altra", "brooks", "columbia", "new balance", "nike", "salomon"],
    // badge: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "teal",
      "white",
    ],
  },
  womenclimbing: {
    gender: ["women"],
    sport: ["climbing"],
    brand: [
      "black diamond",
      "la sportiva",
      "ocun",
      "red chili",
      "scarpa",
      "tenaya",
    ],
    // badge: ["featured", "new", "sale"],
    sizes: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "green",
      "lightblue",
      "orange",
      "pink",
      "red",
      "sienna",
      "teal",
      "white",
      "yellow",
    ],
  },
  //   collection
  womenfeatured: {
    gender: ["women"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "altra",
      "asics",
      "black diamond",
      "brooks",
      "columbia",
      "new balance",
      "nike",
      "on",
      "salomon",
      "scarpa",
    ],
    // badge: ["featured"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "slateblue",
      "teal",
      "white",
    ],
  },
  womennew: {
    gender: ["women"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "altra",
      "asics",
      "black diamond",
      "columbia",
      "la sportiva",
      "new balance",
      "nike",
      "ocun",
      "scarpa",
      "tenaya",
      "under armour",
    ],
    // badge: ["new"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "yellow",
    ],
  },
  womensale: {
    gender: ["women"],
    sport: ["climbing", "training", "hiking", "running"],
    brand: [
      "altra",
      "asics",
      "black diamond",
      "columbia",
      "la sportiva",
      "new balance",
      "nike",
      "ocun",
      "scarpa",
      "tenaya",
      "under armour",
    ],
    // badge: ["sale"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "yellow",
    ],
  },
  //   brand
  womenadidas: {
    gender: ["women"],
    sport: ["training"],
    brand: ["adidas"],
    // badge: ["sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
    ],
    colors: ["black", "pink", "white"],
  },
  womenaltra: {
    gender: ["women"],
    sport: ["hiking", "running"],
    brand: ["altra"],
    // badge: ["new", "sale", "featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: [
      "darkblue",
      "green",
      "lightblue",
      "orange",
      "slateblue",
      "teal",
      "white",
    ],
  },
  womenasics: {
    gender: ["women"],
    sport: ["running"],
    brand: ["asics"],
    // badge: ["new", "featured", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: ["black", "blue", "darkblue", "grey", "lightblue", "teal", "white"],
  },
  "womenblack diamond": {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["black diamond"],
    // badge: ["featured", "sale", "new"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8"],
    colors: ["blue", "lightblue", "pink", "red", "sienna"],
  },
  womenbrooks: {
    gender: ["women"],
    sport: ["running", "hiking"],
    brand: ["brooks"],
    // badge: ["featured", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: [
      "beige",
      "black",
      "darkblue",
      "grey",
      "lightblue",
      "red",
      "slateblue",
      "teal",
      "white",
    ],
  },
  womencolumbia: {
    gender: ["women"],
    sport: ["hiking"],
    brand: ["columbia"],
    // badge: ["new", "featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "12",
    ],
    colors: ["black", "blue", "grey", "sienna", "white"],
  },
  womeninov: {
    gender: ["women"],
    sport: ["running", "training"],
    brand: ["inov"],
    sizes: ["6", "7", "7.5", "8", "9", "9.5"],
    colors: ["black", "darkblue", "lightblue", "red"],
  },
  "womenla sportiva": {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["la sportiva"],
    // badge: ["sale", "new"],
    sizes: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
    ],
    colors: ["beige", "lightblue", "orange", "teal", "yellow"],
  },
  "womennew balance": {
    gender: ["women"],
    sport: ["running", "training", "hiking"],
    brand: ["new balance"],
    // badge: ["new", "sale", "featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "pink",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  womennike: {
    gender: ["women"],
    sport: ["training", "running", "hiking"],
    brand: ["nike"],
    // badge: ["sale", "new", "featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: ["beige", "black", "blue", "green", "grey", "red", "teal"],
  },
  womenocun: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["ocun"],
    // badge: ["new"],
    sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5"],
    colors: ["red"],
  },
  womenon: {
    gender: ["women"],
    sport: ["running"],
    brand: ["on"],
    // badge: ["sale", "featured"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
    ],
    colors: ["beige", "black", "blue", "darkblue", "grey"],
  },
  "womenred chili": {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["red chili"],
    sizes: ["4.5", "5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9"],
    colors: ["blue", "green", "white"],
  },
  womensalomon: {
    gender: ["women"],
    sport: ["hiking"],
    brand: ["salomon"],
    // badge: ["featured", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: ["darkblue", "lightblue", "red", "teal", "white"],
  },
  womensaucony: {
    gender: ["women"],
    sport: ["running"],
    brand: ["saucony"],
    // badge: ["sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
    ],
    colors: ["beige", "black", "grey", "lightblue", "white", "yellow"],
  },
  womenscarpa: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["scarpa"],
    // badge: ["featured", "new", "sale"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "sienna", "teal", "white"],
  },
  womentenaya: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["tenaya"],
    // badge: ["new"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11.5",
    ],
    colors: ["blue", "green", "lightblue", "teal"],
  },
  "womenunder armour": {
    gender: ["women"],
    sport: ["training", "running"],
    brand: ["under armour"],
    // badge: ["new", "sale"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "12",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "lightblue",
      "pink",
      "red",
      "sienna",
      "white",
    ],
  },

  // BRAND
  adidas: {
    gender: ["women", "men"],
    sport: ["training", "hiking", "running"],
    brand: ["adidas"],
    // bagde: ["featured", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "14.5",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "pink",
      "red",
      "sienna",
      "white",
    ],
  },
  altra: {
    gender: ["men", "women"],
    sport: ["hiking", "running"],
    brand: ["altra"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "slateblue",
      "teal",
      "white",
    ],
  },
  asics: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: ["asics"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  "black diamond": {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["black diamond"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "11.5",
      "12",
      "13.5",
      "14",
    ],
    colors: [
      "blue",
      "grey",
      "lightblue",
      "pink",
      "red",
      "sienna",
      "white",
      "yellow",
    ],
  },
  brooks: {
    gender: ["women", "men"],
    sport: ["hiking", "running"],
    brand: ["brooks"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  columbia: {
    gender: ["women", "men"],
    sport: ["hiking"],
    brand: ["columbia"],
    // bagde: ["featured", "new"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
      "14",
      "15",
    ],
    colors: ["beige", "black", "blue", "green", "grey", "sienna", "white"],
  },
  inov: {
    gender: ["men", "women"],
    sport: ["training", "hiking", "running"],
    brand: ["inov"],
    // bagde: ["featured", "new"],
    sizes: [
      "6",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: ["black", "darkblue", "grey", "lightblue", "red", "teal"],
  },
  "la sportiva": {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["la sportiva"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "teal",
      "white",
      "yellow",
    ],
  },
  "new balance": {
    gender: ["women", "men"],
    sport: ["training", "hiking", "running"],
    brand: ["new balance"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "orange",
      "pink",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  nike: {
    gender: ["women", "men"],
    sport: ["training", "hiking", "running"],
    brand: ["nike"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "red",
      "teal",
      "white",
    ],
  },
  ocun: {
    gender: ["women", "men"],
    sport: ["climbing"],
    brand: ["ocun"],
    // bagde: ["featured", "new"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: ["black", "red", "teal"],
  },
  on: {
    gender: ["men", "women"],
    sport: ["running"],
    brand: ["on"],
    // bagde: ["featured", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: ["beige", "black", "blue", "darkblue", "grey", "lightblue"],
  },
  "red chili": {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["red chili"],
    // bagde: ["featured", "sale"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: ["black", "blue", "green", "red", "white"],
  },
  salomon: {
    gender: ["men", "women"],
    sport: ["hiking"],
    brand: ["salomon"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "lightblue",
      "red",
      "sienna",
      "teal",
      "white",
    ],
  },
  saucony: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: ["saucony"],
    // bagde: ["new", "sale"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    colors: ["beige", "black", "blue", "grey", "lightblue", "white", "yellow"],
  },
  scarpa: {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["scarpa"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "orange", "sienna", "teal", "white", "yellow"],
  },
  tenaya: {
    gender: ["women", "men"],
    sport: ["climbing"],
    brand: ["tenaya"],
    // bagde: ["featured", "new"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11.5",
    ],
    colors: ["blue", "green", "lightblue", "teal"],
  },
  "under armour": {
    gender: ["men", "women"],
    sport: ["training", "running"],
    brand: ["under armour"],
    // bagde: ["featured", "new", "sale"],
    sizes: [
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "13.5",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
};
