export type SHOPFILTERSTYPE = {
  [key: string]: {
    gender: string[];
    sport: string[];
    brand: string[];
    colors: string[];
    sizes: string[];
  };
};
export type FilterKeys = "gender" | "sport" | "brand" | "sizes" | "colors";

export const SHOP_FILTERS: SHOPFILTERSTYPE = {
  // GENDER
  men: {
    gender: ["men"],
    sport: ["training", "running", "climbing", "hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "la sportiva",
      "new balance",
      "nike",
      "on",
      "red chili",
      "reebok",
      "salomon",
      "saucony",
      "scarpa",
      "under armour",
    ],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "aqua",
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  women: {
    gender: ["women"],
    sport: ["running", "training", "climbing", "hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "la sportiva",
      "new balance",
      "nike",
      "on",
      "red chili",
      "reebok",
      "salomon",
      "scarpa",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  // SPORTS
  running: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "on",
      "salomon",
      "saucony",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  training: {
    gender: ["men", "women"],
    sport: ["training"],
    brand: ["adidas", "altra", "new balance", "nike", "reebok", "under armour"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "sienna",
      "teal",
      "white",
    ],
  },
  hiking: {
    gender: ["men", "women"],
    sport: ["hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "salomon",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "aqua",
      "beige",
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  climbing: {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["la sportiva", "red chili", "scarpa"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "grey",
      "lightgreen",
      "orange",
      "teal",
      "white",
      "yellow",
    ],
  },
  // COLLECTIONS
  featured: {
    gender: ["men", "women"],
    sport: ["training", "running", "climbing", "hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "red chili",
      "reebok",
      "salomon",
      "saucony",
      "scarpa",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "aqua",
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  sale: {
    gender: ["women", "men"],
    sport: ["running", "climbing", "training", "hiking"],
    brand: [
      "adidas",
      "brooks",
      "new balance",
      "nike",
      "red chili",
      "reebok",
      "scarpa",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "sienna",
      "teal",
      "white",
    ],
  },
  // BRANDS
  adidas: {
    gender: ["women", "men"],
    sport: ["training", "running", "hiking"],
    brand: ["adidas"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    colors: [
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "pink",
      "sienna",
      "white",
    ],
  },
  altra: {
    gender: ["men", "women"],
    sport: ["running", "hiking", "training"],
    brand: ["altra"],
    sizes: [
      "6",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "aqua",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "pink",
      "teal",
      "white",
      "yellow",
    ],
  },
  asics: {
    gender: ["men", "women"],
    sport: ["running", "hiking"],
    brand: ["asics"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "red",
      "teal",
      "yellow",
    ],
  },
  brooks: {
    gender: ["women", "men"],
    sport: ["hiking", "running"],
    brand: ["brooks"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "pink",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  "la sportiva": {
    gender: ["women", "men"],
    sport: ["climbing"],
    brand: ["la sportiva"],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "12",
      "12.5",
      "13",
    ],
    colors: ["beige", "lightgreen", "yellow"],
  },
  "new balance": {
    gender: ["men", "women"],
    sport: ["running", "training", "hiking"],
    brand: ["new balance"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "sienna",
    ],
  },
  nike: {
    gender: ["women", "men"],
    sport: ["running", "training", "hiking"],
    brand: ["nike"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  on: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: ["on"],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
    ],
    colors: ["black", "darkblue", "orange"],
  },
  "red chili": {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["red chili"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "blue", "lightgreen", "orange"],
  },
  reebok: {
    gender: ["men", "women"],
    sport: ["training"],
    brand: ["reebok"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8.5", "9", "9.5", "10"],
    colors: ["orange", "white"],
  },
  salomon: {
    gender: ["men", "women"],
    sport: ["hiking", "running"],
    brand: ["salomon"],
    sizes: [
      "5",
      "6",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["beige", "black", "blue", "grey", "lightblue"],
  },
  saucony: {
    gender: ["men"],
    sport: ["running"],
    brand: ["saucony"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: ["black", "darkblue", "lightblue", "white"],
  },
  scarpa: {
    gender: ["women", "men"],
    sport: ["climbing"],
    brand: ["scarpa"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: ["black", "blue", "green", "grey", "teal", "white"],
  },
  "under armour": {
    gender: ["men", "women"],
    sport: ["training", "running", "hiking"],
    brand: ["under armour"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: ["beige", "black", "blue", "green", "lightgreen", "teal", "white"],
  },

  // GENDER_SPORT
  menrunning: {
    gender: ["men"],
    sport: ["running"],
    brand: [
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "on",
      "salomon",
      "saucony",
      "under armour",
    ],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "orange",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  mentraining: {
    gender: ["men"],
    sport: ["training"],
    brand: ["adidas", "altra", "nike", "reebok", "under armour"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "green",
      "grey",
      "lightblue",
      "sienna",
      "white",
    ],
  },
  menhiking: {
    gender: ["men"],
    sport: ["hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "salomon",
      "under armour",
    ],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "aqua",
      "beige",
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  menclimbing: {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["la sportiva", "red chili", "scarpa"],
    sizes: [
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["beige", "black", "lightgreen", "orange", "teal", "yellow"],
  },
  womenrunning: {
    gender: ["women"],
    sport: ["running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "on",
      "salomon",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "teal",
      "white",
      "yellow",
    ],
  },
  womentraining: {
    gender: ["women"],
    sport: ["training"],
    brand: ["adidas", "new balance", "nike", "reebok", "under armour"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: [
      "beige",
      "black",
      "darkblue",
      "green",
      "lightgreen",
      "orange",
      "pink",
      "teal",
      "white",
    ],
  },
  womenhiking: {
    gender: ["women"],
    sport: ["hiking"],
    brand: ["adidas", "asics", "brooks", "new balance", "nike", "under armour"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: [
      "beige",
      "black",
      "darkblue",
      "grey",
      "lightblue",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
    ],
  },
  womenclimbing: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["la sportiva", "red chili", "scarpa"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: [
      "black",
      "blue",
      "grey",
      "lightgreen",
      "orange",
      "white",
      "yellow",
    ],
  },

  // GENDER_COLLECTIONS
  menfeatured: {
    gender: ["men"],
    sport: ["training", "running", "climbing", "hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "red chili",
      "reebok",
      "salomon",
      "saucony",
      "scarpa",
      "under armour",
    ],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "aqua",
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  mensale: {
    gender: ["men"],
    sport: ["training", "running"],
    brand: ["brooks", "nike", "reebok"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "teal", "white"],
  },
  womenfeatured: {
    gender: ["women"],
    sport: ["running", "training", "climbing", "hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "scarpa",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  womensale: {
    gender: ["women"],
    sport: ["running", "climbing", "training", "hiking"],
    brand: [
      "adidas",
      "brooks",
      "new balance",
      "nike",
      "red chili",
      "reebok",
      "scarpa",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: [
      "beige",
      "blue",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "sienna",
      "teal",
      "white",
    ],
  },

  // GENDER_BRAND
  menadidas: {
    gender: ["men"],
    sport: ["training", "hiking"],
    brand: ["adidas"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    colors: ["black", "grey", "lightblue", "orange", "white"],
  },
  menaltra: {
    gender: ["men"],
    sport: ["running", "hiking", "training"],
    brand: ["altra"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "aqua",
      "black",
      "darkblue",
      "green",
      "grey",
      "teal",
      "white",
      "yellow",
    ],
  },
  menasics: {
    gender: ["men"],
    sport: ["running", "hiking"],
    brand: ["asics"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "red",
      "teal",
      "yellow",
    ],
  },
  menbrooks: {
    gender: ["men"],
    sport: ["hiking", "running"],
    brand: ["brooks"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "black",
      "blue",
      "darkblue",
      "grey",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  menlasportiva: {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["la sportiva"],
    sizes: ["7", "8.5", "9", "9.5", "10", "10.5", "11", "12", "12.5", "13"],
    colors: ["beige", "lightgreen"],
  },
  mennewbalance: {
    gender: ["men"],
    sport: ["running", "hiking"],
    brand: ["new balance"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: ["black", "blue", "darkblue", "lightgreen", "orange", "sienna"],
  },
  mennike: {
    gender: ["men"],
    sport: ["running", "training", "hiking"],
    brand: ["nike"],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "black",
      "blue",
      "lightblue",
      "orange",
      "sienna",
      "slateblue",
      "teal",
    ],
  },
  menon: {
    gender: ["men"],
    sport: ["running"],
    brand: ["on"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5"],
    colors: ["black"],
  },
  menredchili: {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["red chili"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "lightgreen", "orange"],
  },
  menreebok: {
    gender: ["men"],
    sport: ["training"],
    brand: ["reebok"],
    sizes: ["7", "7.5", "8.5", "9", "9.5", "10"],
    colors: ["white"],
  },
  mensalomon: {
    gender: ["men"],
    sport: ["hiking", "running"],
    brand: ["salomon"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["beige", "black", "blue", "grey", "lightblue"],
  },
  mensaucony: {
    gender: ["men"],
    sport: ["running"],
    brand: ["saucony"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: ["black", "darkblue", "lightblue", "white"],
  },
  menscarpa: {
    gender: ["men"],
    sport: ["climbing"],
    brand: ["scarpa"],
    sizes: [
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
    ],
    colors: ["green", "grey", "teal", "yellow"],
  },
  "menunder armour": {
    gender: ["men"],
    sport: ["training", "running", "hiking"],
    brand: ["under armour"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: ["beige", "black", "blue", "green", "white"],
  },

  womenadidas: {
    gender: ["women"],
    sport: ["training", "running", "hiking"],
    brand: ["adidas"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"],
    colors: ["black", "darkblue", "green", "pink", "sienna"],
  },
  womenaltra: {
    gender: ["women"],
    sport: ["running"],
    brand: ["altra"],
    sizes: ["6", "7", "7.5", "8", "9", "9.5", "10"],
    colors: ["blue", "pink"],
  },
  womenasics: {
    gender: ["women"],
    sport: ["running", "hiking"],
    brand: ["asics"],
    sizes: [
      "5",
      "5.5",
      "6",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
      "14",
      "15",
    ],
    colors: ["black", "darkblue", "red", "teal", "yellow"],
  },
  womenbrooks: {
    gender: ["women"],
    sport: ["hiking", "running"],
    brand: ["brooks"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "darkblue", "grey", "pink", "teal", "white"],
  },
  womenlasportiva: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["la sportiva"],
    sizes: ["5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"],
    colors: ["yellow"],
  },
  womennewbalance: {
    gender: ["women"],
    sport: ["running", "training", "hiking"],
    brand: ["new balance"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: ["black", "lightblue", "lightgreen", "orange", "pink", "red"],
  },
  womennike: {
    gender: ["women"],
    sport: ["running", "training", "hiking"],
    brand: ["nike"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11",
      "11.5",
      "12",
    ],
    colors: [
      "beige",
      "black",
      "lightblue",
      "lightgreen",
      "pink",
      "slateblue",
      "white",
    ],
  },
  womenon: {
    gender: ["women"],
    sport: ["running"],
    brand: ["on"],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
    ],
    colors: ["darkblue", "orange"],
  },
  womenredchili: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["red chili"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: ["blue", "lightgreen", "orange"],
  },
  womenreebok: {
    gender: ["women"],
    sport: ["training"],
    brand: ["reebok"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8.5", "9", "9.5", "10"],
    colors: ["orange", "white"],
  },
  womensalomon: {
    gender: ["women"],
    sport: ["running"],
    brand: ["salomon"],
    sizes: ["5", "6", "7", "7.5", "8", "8.5"],
    colors: ["beige"],
  },
  womensaucony: {
    gender: ["women"],
    sport: ["running"],
    brand: ["saucony"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
    ],
    colors: ["black", "teal", "white", "yellow"],
  },
  womenscarpa: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["scarpa"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: ["black", "blue", "grey", "white"],
  },
  "womenunder armour": {
    gender: ["women"],
    sport: ["training", "running", "hiking"],
    brand: ["under armour"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "12",
    ],
    colors: ["beige", "black", "lightgreen", "teal"],
  },

  // SPORT_COLLECTION
  runningfeatured: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "salomon",
      "saucony",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  runningsale: {
    gender: ["women", "men"],
    sport: ["running"],
    brand: ["brooks", "new balance", "nike"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["beige", "black", "lightblue", "lightgreen", "orange", "teal"],
  },
  trainingfeatured: {
    gender: ["men", "women"],
    sport: ["training"],
    brand: ["adidas", "altra", "new balance", "nike", "reebok", "under armour"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "beige",
      "black",
      "blue",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "pink",
      "sienna",
      "white",
    ],
  },
  trainingsale: {
    gender: ["men", "women"],
    sport: ["training"],
    brand: ["nike", "reebok"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8.5", "9", "9.5", "10", "12"],
    colors: ["black", "orange", "white"],
  },
  hikingfeatured: {
    gender: ["men", "women"],
    sport: ["hiking"],
    brand: [
      "adidas",
      "altra",
      "asics",
      "brooks",
      "new balance",
      "nike",
      "salomon",
      "under armour",
    ],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    colors: [
      "aqua",
      "beige",
      "black",
      "darkblue",
      "green",
      "grey",
      "lightblue",
      "lightgreen",
      "orange",
      "pink",
      "red",
      "sienna",
      "slateblue",
      "teal",
      "white",
      "yellow",
    ],
  },
  hikingsale: {
    gender: ["women"],
    sport: ["hiking"],
    brand: ["adidas"],
    sizes: ["5", "5.5", "7.5", "9"],
    colors: ["pink", "sienna"],
  },
  climbingfeatured: {
    gender: ["men", "women"],
    sport: ["climbing"],
    brand: ["red chili", "scarpa"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: ["black", "grey", "teal", "white"],
  },
  climbingsale: {
    gender: ["women"],
    sport: ["climbing"],
    brand: ["red chili", "scarpa"],
    sizes: ["5", "5.5", "6", "6.5", "7"],
    colors: ["blue", "orange", "white"],
  },
};
