export type SHOPFILTERSTYPE = {
    [key: string]: {
      gender: string[];
      category: string[];
      brand: string[];
      badge?: string[];
      sizes: string[];
      colors: string[];
    };
  };
  export type FilterKeys = "gender" | "category" | "brand" | "sizes" | "colors";
  
  export const SHOP_FILTERS: SHOPFILTERSTYPE = {
    // "": {
    //   gender: ["women", "men"],
    //   category: ["running", "cross training", "hiking", "climbing"],
    //   brand: [
    //     "adidas",
    //     "altra",
    //     "asics",
    //     "black diamond",
    //     "brooks",
    //     "columbia",
    //     "inov",
    //     "la sportiva",
    //     "new balance",
    //     "nike",
    //     "ocun",
    //     "on",
    //     "red chili",
    //     "salomon",
    //     "saucony",
    //     "scarpa",
    //     "tenaya",
    //     "under armour",
    //   ],
    //   // badge: ["new", "best seller", "sale"],
    //   sizes: [
    //     "4",
    //     "4.5",
    //     "5",
    //     "5.5",
    //     "6",
    //     "6.5",
    //     "7",
    //     "7.5",
    //     "8",
    //     "8.5",
    //     "9",
    //     "9.5",
    //     "10",
    //     "10.5",
    //     "11",
    //     "11.5",
    //     "12",
    //     "12.5",
    //     "13",
    //     "13.5",
    //     "14",
    //     "14.5",
    //     "15",
    //   ],
    //   colors: [
    //     "beige",
    //     "black",
    //     "blue",
    //     "darkblue",
    //     "green",
    //     "grey",
    //     "lightblue",
    //     "orange",
    //     "pink",
    //     "red",
    //     "sienna",
    //     "slateblue",
    //     "teal",
    //     "white",
    //     "yellow",
    //   ],
    // },
    // COLLECTIONS
    "best seller": {
      gender: ["women", "men"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "columbia",
        "inov",
        "la sportiva",
        "new balance",
        "nike",
        "ocun",
        "on",
        "red chili",
        "salomon",
        "scarpa",
        "tenaya",
        "under armour",
      ],
      // bagde: ["best seller"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    new: {
      gender: ["women", "men"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "columbia",
        "inov",
        "la sportiva",
        "new balance",
        "nike",
        "ocun",
        "salomon",
        "saucony",
        "scarpa",
        "tenaya",
        "under armour",
      ],
      // bagde: ["new"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    sale: {
      gender: ["women", "men"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "la sportiva",
        "new balance",
        "nike",
        "on",
        "red chili",
        "salomon",
        "saucony",
        "scarpa",
        "under armour",
      ],
      // bagde: ["sale"],
      sizes: [
        "4",
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "red",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    // CATEGORY
    running: {
      gender: ["women", "men"],
      category: ["running"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "brooks",
        "inov",
        "new balance",
        "nike",
        "on",
        "saucony",
        "under armour",
      ],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    "runningbest seller": {
      gender: ["women", "men"],
      category: ["running"],
      brand: ["adidas", "altra", "asics", "brooks", "new balance", "nike", "on"],
      // bagde: ["best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    runningnew: {
      gender: ["women", "men"],
      category: ["running"],
      brand: [
        "altra",
        "asics",
        "brooks",
        "new balance",
        "nike",
        "saucony",
        "under armour",
      ],
      // bagde: ["new"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "pink",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    runningsale: {
      gender: ["women", "men"],
      category: ["running"],
      brand: ["adidas", "altra", "asics", "brooks", "nike", "on", "saucony"],
      // bagde: ["sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "red",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    "cross training": {
      gender: ["men", "women"],
      category: ["cross training"],
      brand: ["adidas", "inov", "new balance", "nike", "under armour"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    "cross trainingbest seller": {
      gender: ["men", "women"],
      category: ["cross training"],
      brand: ["inov", "new balance", "nike", "under armour"],
      // bagde: ["best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "red",
        "teal",
      ],
    },
    "cross trainingnew": {
      gender: ["men", "women"],
      category: ["cross training"],
      brand: ["new balance", "nike", "under armour"],
      // bagde: ["new"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: ["beige", "black", "darkblue", "grey", "red", "slateblue", "white"],
    },
    "cross trainingsale": {
      gender: ["women", "men"],
      category: ["cross training"],
      brand: ["adidas", "new balance", "nike", "under armour"],
      // bagde: ["sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: ["black", "darkblue", "grey", "red", "teal", "white"],
    },
    hiking: {
      gender: ["women", "men"],
      category: ["hiking"],
      brand: [
        "adidas",
        "altra",
        "brooks",
        "columbia",
        "inov",
        "new balance",
        "nike",
        "salomon",
      ],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "14.5",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "teal",
        "white",
      ],
    },
    "hikingbest seller": {
      gender: ["women", "men"],
      category: ["hiking"],
      brand: ["altra", "brooks", "columbia", "new balance", "nike", "salomon"],
      // bagde: ["best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "sienna",
        "teal",
        "white",
      ],
    },
    hikingnew: {
      gender: ["women", "men"],
      category: ["hiking"],
      brand: ["altra", "brooks", "columbia", "inov", "new balance", "salomon"],
      // bagde: ["new"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "orange",
        "red",
        "sienna",
        "teal",
      ],
    },
    hikingsale: {
      gender: ["women", "men"],
      category: ["hiking"],
      brand: ["adidas", "new balance", "salomon"],
      // bagde: ["sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: ["darkblue", "lightblue", "orange"],
    },
    climbing: {
      gender: ["men", "women"],
      category: ["climbing"],
      brand: [
        "black diamond",
        "la sportiva",
        "ocun",
        "red chili",
        "scarpa",
        "tenaya",
      ],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "4",
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "pink",
        "red",
        "sienna",
        "teal",
        "white",
        "yellow",
      ],
    },
    "climbingbest seller": {
      gender: ["men", "women"],
      category: ["climbing"],
      brand: [
        "black diamond",
        "la sportiva",
        "ocun",
        "red chili",
        "scarpa",
        "tenaya",
      ],
      // bagde: ["best seller"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
      ],
      colors: [
        "black",
        "blue",
        "grey",
        "lightblue",
        "orange",
        "red",
        "teal",
        "white",
      ],
    },
    climbingnew: {
      gender: ["men", "women"],
      category: ["climbing"],
      brand: ["black diamond", "la sportiva", "ocun", "scarpa", "tenaya"],
      // bagde: ["new"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
      ],
      colors: [
        "black",
        "blue",
        "green",
        "pink",
        "red",
        "sienna",
        "teal",
        "yellow",
      ],
    },
    climbingsale: {
      gender: ["women", "men"],
      category: ["climbing"],
      brand: ["black diamond", "la sportiva", "red chili", "scarpa"],
      // bagde: ["sale"],
      sizes: [
        "4",
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "11.5",
      ],
      colors: ["black", "blue", "red", "teal", "yellow"],
    },
    //   MEN
    men: {
      gender: ["men"],
      category: ["running", "cross training", "hiking", "climbing"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "columbia",
        "inov",
        "la sportiva",
        "new balance",
        "nike",
        "ocun",
        "on",
        "red chili",
        "salomon",
        "saucony",
        "scarpa",
        "tenaya",
        "under armour",
      ],
      // badge: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "14.5",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    //   MEN CATEGORY
    menrunning: {
      gender: ["men"],
      category: ["running"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "brooks",
        "inov",
        "new balance",
        "nike",
        "on",
        "saucony",
        "under armour",
      ],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    "mencross training": {
      gender: ["men"],
      category: ["cross training"],
      brand: ["adidas", "inov", "new balance", "nike", "under armour"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "red",
        "sienna",
        "teal",
        "white",
      ],
    },
    menhiking: {
      gender: ["men"],
      category: ["hiking"],
      brand: ["adidas", "altra", "brooks", "columbia", "inov", "nike", "salomon"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "14.5",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "teal",
        "white",
      ],
    },
    menclimbing: {
      gender: ["men"],
      category: ["climbing"],
      brand: [
        "black diamond",
        "la sportiva",
        "ocun",
        "red chili",
        "scarpa",
        "tenaya",
      ],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
      ],
      colors: [
        "black",
        "blue",
        "green",
        "grey",
        "orange",
        "red",
        "teal",
        "white",
        "yellow",
      ],
    },
    //   MEN COLLECTION
    "menbest seller": {
      gender: ["men"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "columbia",
        "inov",
        "la sportiva",
        "new balance",
        "nike",
        "ocun",
        "red chili",
        "salomon",
        "scarpa",
        "tenaya",
        "under armour",
      ],
      // bagde: ["best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "teal",
        "white",
      ],
    },
    mennew: {
      gender: ["men"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "altra",
        "asics",
        "brooks",
        "columbia",
        "inov",
        "la sportiva",
        "new balance",
        "nike",
        "salomon",
        "saucony",
        "scarpa",
        "under armour",
      ],
      // bagde: ["new"],
      sizes: [
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    mensale: {
      gender: ["men"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "new balance",
        "nike",
        "on",
        "red chili",
        "saucony",
        "under armour",
      ],
      // bagde: ["sale"],
      sizes: [
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "teal",
        "white",
        "yellow",
      ],
    },
    // MEN BRAND
    menadidas: {
      gender: ["men"],
      category: ["cross training", "hiking", "running"],
      brand: ["adidas"],
      // bagde: ["best seller", "sale"],
      sizes: [
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "14.5",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "white",
      ],
    },
    menaltra: {
      gender: ["men"],
      category: ["hiking", "running"],
      brand: ["altra"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: ["black", "darkblue", "grey", "teal"],
    },
    menasics: {
      gender: ["men"],
      category: ["running"],
      brand: ["asics"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    "menblack diamond": {
      gender: ["men"],
      category: ["climbing"],
      brand: ["black diamond"],
      // bagde: ["best seller", "sale"],
      sizes: ["7", "8", "11.5", "12", "13.5", "14"],
      colors: ["blue", "grey", "white", "yellow"],
    },
    menbrooks: {
      gender: ["men"],
      category: ["hiking", "running"],
      brand: ["brooks"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "sienna",
        "teal",
        "white",
      ],
    },
    mencolumbia: {
      gender: ["men"],
      category: ["hiking"],
      brand: ["columbia"],
      // bagde: ["best seller", "new"],
      sizes: [
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "13",
        "14",
        "15",
      ],
      colors: ["beige", "black", "green", "grey", "white"],
    },
    meninov: {
      gender: ["men"],
      category: ["cross training", "hiking", "running"],
      brand: ["inov"],
      // bagde: ["best seller", "new"],
      sizes: [
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: ["grey", "red", "teal"],
    },
    "menla sportiva": {
      gender: ["men"],
      category: ["climbing"],
      brand: ["la sportiva"],
      // bagde: ["best seller", "new"],
      sizes: [
        "6",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
      ],
      colors: ["black", "blue", "green", "grey", "white", "yellow"],
    },
    "mennew balance": {
      gender: ["men"],
      category: ["cross training", "running"],
      brand: ["new balance"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: ["black", "grey", "red", "white"],
    },
    mennike: {
      gender: ["men"],
      category: ["cross training", "hiking", "running"],
      brand: ["nike"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "teal",
        "white",
      ],
    },
    menocun: {
      gender: ["men"],
      category: ["climbing"],
      brand: ["ocun"],
      // bagde: ["best seller"],
      sizes: [
        "6",
        "6.5",
        "7",
        "8",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
      ],
      colors: ["black", "teal"],
    },
    menon: {
      gender: ["men"],
      category: ["running"],
      brand: ["on"],
      // bagde: ["sale"],
      sizes: [
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: ["black", "blue", "lightblue"],
    },
    "menred chili": {
      gender: ["men"],
      category: ["climbing"],
      brand: ["red chili"],
      // bagde: ["best seller", "sale"],
      sizes: [
        "5.5",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
      ],
      colors: ["black", "blue", "red", "white"],
    },
    mensalomon: {
      gender: ["men"],
      category: ["hiking"],
      brand: ["salomon"],
      // bagde: ["best seller", "new"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: ["black", "blue", "darkblue", "lightblue", "red", "sienna", "teal"],
    },
    mensaucony: {
      gender: ["men"],
      category: ["running"],
      brand: ["saucony"],
      // bagde: ["new", "sale"],
      sizes: [
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "13",
      ],
      colors: ["black", "blue", "grey", "white"],
    },
    menscarpa: {
      gender: ["men"],
      category: ["climbing"],
      brand: ["scarpa"],
      // bagde: ["best seller", "new"],
      sizes: [
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
      ],
      colors: ["black", "orange", "white", "yellow"],
    },
    mentenaya: {
      gender: ["men"],
      category: ["climbing"],
      brand: ["tenaya"],
      // bagde: ["best seller"],
      sizes: ["8"],
      colors: ["blue"],
    },
    "menunder armour": {
      gender: ["men"],
      category: ["cross training", "running"],
      brand: ["under armour"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    // WOMEN
    women: {
      gender: ["women"],
      category: ["running", "cross training", "hiking", "climbing"],
      brand: [
        "adidas",
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "columbia",
        "inov",
        "la sportiva",
        "new balance",
        "nike",
        "ocun",
        "on",
        "red chili",
        "salomon",
        "saucony",
        "scarpa",
        "tenaya",
        "under armour",
      ],
      // badge: ["best seller", "new", "sale"],
      sizes: [
        "4",
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    //   category
    womenrunning: {
      gender: ["women"],
      category: ["running"],
      brand: [
        "altra",
        "asics",
        "brooks",
        "inov",
        "new balance",
        "nike",
        "on",
        "saucony",
        "under armour",
      ],
      // badge: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "pink",
        "red",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    "womencross training": {
      gender: ["women"],
      category: ["cross training"],
      brand: ["adidas", "inov", "new balance", "nike", "under armour"],
      // "badge": [
      //     "best seller",
      //     "new",
      //     "sale",
      // ],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    womenhiking: {
      gender: ["women"],
      category: ["hiking"],
      brand: ["altra", "brooks", "columbia", "new balance", "nike", "salomon"],
      // badge: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "teal",
        "white",
      ],
    },
    womenclimbing: {
      gender: ["women"],
      category: ["climbing"],
      brand: [
        "black diamond",
        "la sportiva",
        "ocun",
        "red chili",
        "scarpa",
        "tenaya",
      ],
      // badge: ["best seller", "new", "sale"],
      sizes: [
        "4",
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "green",
        "lightblue",
        "orange",
        "pink",
        "red",
        "sienna",
        "teal",
        "white",
        "yellow",
      ],
    },
    //   collection
    "womenbest seller": {
      gender: ["women"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "altra",
        "asics",
        "black diamond",
        "brooks",
        "columbia",
        "new balance",
        "nike",
        "on",
        "salomon",
        "scarpa",
      ],
      // badge: ["best seller"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "slateblue",
        "teal",
        "white",
      ],
    },
    womennew: {
      gender: ["women"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "altra",
        "asics",
        "black diamond",
        "columbia",
        "la sportiva",
        "new balance",
        "nike",
        "ocun",
        "scarpa",
        "tenaya",
        "under armour",
      ],
      // badge: ["new"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "14",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "orange",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "yellow",
      ],
    },
    womensale: {
      gender: ["women"],
      category: ["climbing", "cross training", "hiking", "running"],
      brand: [
        "altra",
        "asics",
        "black diamond",
        "columbia",
        "la sportiva",
        "new balance",
        "nike",
        "ocun",
        "scarpa",
        "tenaya",
        "under armour",
      ],
      // badge: ["sale"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "14",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "orange",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "yellow",
      ],
    },
    //   brand
    womenadidas: {
      gender: ["women"],
      category: ["cross training"],
      brand: ["adidas"],
      // badge: ["sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
      ],
      colors: ["black", "pink", "white"],
    },
    womenaltra: {
      gender: ["women"],
      category: ["hiking", "running"],
      brand: ["altra"],
      // badge: ["new", "sale", "best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
      ],
      colors: [
        "darkblue",
        "green",
        "lightblue",
        "orange",
        "slateblue",
        "teal",
        "white",
      ],
    },
    womenasics: {
      gender: ["women"],
      category: ["running"],
      brand: ["asics"],
      // badge: ["new", "best seller", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
      ],
      colors: ["black", "blue", "darkblue", "grey", "lightblue", "teal", "white"],
    },
    "womenblack diamond": {
      gender: ["women"],
      category: ["climbing"],
      brand: ["black diamond"],
      // badge: ["best seller", "sale", "new"],
      sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8"],
      colors: ["blue", "lightblue", "pink", "red", "sienna"],
    },
    womenbrooks: {
      gender: ["women"],
      category: ["running", "hiking"],
      brand: ["brooks"],
      // badge: ["best seller", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
      ],
      colors: [
        "beige",
        "black",
        "darkblue",
        "grey",
        "lightblue",
        "red",
        "slateblue",
        "teal",
        "white",
      ],
    },
    womencolumbia: {
      gender: ["women"],
      category: ["hiking"],
      brand: ["columbia"],
      // badge: ["new", "best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "12",
      ],
      colors: ["black", "blue", "grey", "sienna", "white"],
    },
    womeninov: {
      gender: ["women"],
      category: ["running", "cross training"],
      brand: ["inov"],
      sizes: ["6", "7", "7.5", "8", "9", "9.5"],
      colors: ["black", "darkblue", "lightblue", "red"],
    },
    "womenla sportiva": {
      gender: ["women"],
      category: ["climbing"],
      brand: ["la sportiva"],
      // badge: ["sale", "new"],
      sizes: [
        "4",
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
      ],
      colors: ["beige", "lightblue", "orange", "teal", "yellow"],
    },
    "womennew balance": {
      gender: ["women"],
      category: ["running", "cross training", "hiking"],
      brand: ["new balance"],
      // badge: ["new", "sale", "best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "pink",
        "red",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    womennike: {
      gender: ["women"],
      category: ["cross training", "running", "hiking"],
      brand: ["nike"],
      // badge: ["sale", "new", "best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: ["beige", "black", "blue", "green", "grey", "red", "teal"],
    },
    womenocun: {
      gender: ["women"],
      category: ["climbing"],
      brand: ["ocun"],
      // badge: ["new"],
      sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5"],
      colors: ["red"],
    },
    womenon: {
      gender: ["women"],
      category: ["running"],
      brand: ["on"],
      // badge: ["sale", "best seller"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
      ],
      colors: ["beige", "black", "blue", "darkblue", "grey"],
    },
    "womenred chili": {
      gender: ["women"],
      category: ["climbing"],
      brand: ["red chili"],
      sizes: ["4.5", "5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9"],
      colors: ["blue", "green", "white"],
    },
    womensalomon: {
      gender: ["women"],
      category: ["hiking"],
      brand: ["salomon"],
      // badge: ["best seller", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
      ],
      colors: ["darkblue", "lightblue", "red", "teal", "white"],
    },
    womensaucony: {
      gender: ["women"],
      category: ["running"],
      brand: ["saucony"],
      // badge: ["sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
      ],
      colors: ["beige", "black", "grey", "lightblue", "white", "yellow"],
    },
    womenscarpa: {
      gender: ["women"],
      category: ["climbing"],
      brand: ["scarpa"],
      // badge: ["best seller", "new", "sale"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
      ],
      colors: ["black", "sienna", "teal", "white"],
    },
    womentenaya: {
      gender: ["women"],
      category: ["climbing"],
      brand: ["tenaya"],
      // badge: ["new"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "11.5",
      ],
      colors: ["blue", "green", "lightblue", "teal"],
    },
    "womenunder armour": {
      gender: ["women"],
      category: ["cross training", "running"],
      brand: ["under armour"],
      // badge: ["new", "sale"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "12",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "lightblue",
        "pink",
        "red",
        "sienna",
        "white",
      ],
    },
  
    // BRAND
    adidas: {
      gender: ["women", "men"],
      category: ["cross training", "hiking", "running"],
      brand: ["adidas"],
      // bagde: ["best seller", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "14.5",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "pink",
        "red",
        "sienna",
        "white",
      ],
    },
    altra: {
      gender: ["men", "women"],
      category: ["hiking", "running"],
      brand: ["altra"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "slateblue",
        "teal",
        "white",
      ],
    },
    asics: {
      gender: ["women", "men"],
      category: ["running"],
      brand: ["asics"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    "black diamond": {
      gender: ["men", "women"],
      category: ["climbing"],
      brand: ["black diamond"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "11.5",
        "12",
        "13.5",
        "14",
      ],
      colors: [
        "blue",
        "grey",
        "lightblue",
        "pink",
        "red",
        "sienna",
        "white",
        "yellow",
      ],
    },
    brooks: {
      gender: ["women", "men"],
      category: ["hiking", "running"],
      brand: ["brooks"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
    columbia: {
      gender: ["women", "men"],
      category: ["hiking"],
      brand: ["columbia"],
      // bagde: ["best seller", "new"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "13",
        "14",
        "15",
      ],
      colors: ["beige", "black", "blue", "green", "grey", "sienna", "white"],
    },
    inov: {
      gender: ["men", "women"],
      category: ["cross training", "hiking", "running"],
      brand: ["inov"],
      // bagde: ["best seller", "new"],
      sizes: [
        "6",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: ["black", "darkblue", "grey", "lightblue", "red", "teal"],
    },
    "la sportiva": {
      gender: ["men", "women"],
      category: ["climbing"],
      brand: ["la sportiva"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "4",
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "green",
        "grey",
        "lightblue",
        "orange",
        "teal",
        "white",
        "yellow",
      ],
    },
    "new balance": {
      gender: ["women", "men"],
      category: ["cross training", "hiking", "running"],
      brand: ["new balance"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "grey",
        "lightblue",
        "orange",
        "pink",
        "red",
        "slateblue",
        "teal",
        "white",
        "yellow",
      ],
    },
    nike: {
      gender: ["women", "men"],
      category: ["cross training", "hiking", "running"],
      brand: ["nike"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "red",
        "teal",
        "white",
      ],
    },
    ocun: {
      gender: ["women", "men"],
      category: ["climbing"],
      brand: ["ocun"],
      // bagde: ["best seller", "new"],
      sizes: [
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
      ],
      colors: ["black", "red", "teal"],
    },
    on: {
      gender: ["men", "women"],
      category: ["running"],
      brand: ["on"],
      // bagde: ["best seller", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: ["beige", "black", "blue", "darkblue", "grey", "lightblue"],
    },
    "red chili": {
      gender: ["men", "women"],
      category: ["climbing"],
      brand: ["red chili"],
      // bagde: ["best seller", "sale"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
      ],
      colors: ["black", "blue", "green", "red", "white"],
    },
    salomon: {
      gender: ["men", "women"],
      category: ["hiking"],
      brand: ["salomon"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "14",
      ],
      colors: [
        "black",
        "blue",
        "darkblue",
        "lightblue",
        "red",
        "sienna",
        "teal",
        "white",
      ],
    },
    saucony: {
      gender: ["women", "men"],
      category: ["running"],
      brand: ["saucony"],
      // bagde: ["new", "sale"],
      sizes: [
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "13",
      ],
      colors: ["beige", "black", "blue", "grey", "lightblue", "white", "yellow"],
    },
    scarpa: {
      gender: ["men", "women"],
      category: ["climbing"],
      brand: ["scarpa"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
      ],
      colors: ["black", "orange", "sienna", "teal", "white", "yellow"],
    },
    tenaya: {
      gender: ["women", "men"],
      category: ["climbing"],
      brand: ["tenaya"],
      // bagde: ["best seller", "new"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "11.5",
      ],
      colors: ["blue", "green", "lightblue", "teal"],
    },
    "under armour": {
      gender: ["men", "women"],
      category: ["cross training", "running"],
      brand: ["under armour"],
      // bagde: ["best seller", "new", "sale"],
      sizes: [
        "4.5",
        "5",
        "5.5",
        "6",
        "6.5",
        "7",
        "7.5",
        "8",
        "8.5",
        "9",
        "9.5",
        "10",
        "10.5",
        "11",
        "11.5",
        "12",
        "12.5",
        "13",
        "13.5",
        "14",
        "15",
      ],
      colors: [
        "beige",
        "black",
        "blue",
        "darkblue",
        "green",
        "grey",
        "lightblue",
        "pink",
        "red",
        "sienna",
        "slateblue",
        "teal",
        "white",
      ],
    },
  };
  