import { ProductProps } from "@/types";
import { v4 as uuidv4 } from "uuid";

export const SHOP_DATA: ProductProps[] = [
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "training",
    brand: "under armour",
    name: "project rock 4",
    price: 100,
    colors: ["beige"],
    sizes: ["6", "7", "8", "9"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61E3yRVw9PL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51DcObHeclL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61bA8dp+aZL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71lzKr0SxBL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61qd6ftNrrL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "6", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "8", quantity: 20 },
          { size: "9", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Updated perforated mesh upper provides durable ventilation",
      "Strap & heel overlays for improved lockdown",
      "Bootie design for superior fit, comfort & security",
      "Charged Cushioning midsole absorbs impact & converts it into a responsive burst",
      "UA TriBase maximizes ground contact, promotes natural motion & provides flexibility to grip during lifts",
      "Full rubber outsole for elevated traction & durability",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 82,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "nike",
    name: "flex experience 12",
    price: 120.99,
    colors: ["beige", "lightblue"],
    sizes: ["5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/81-WWFBuTSL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81drd1xq72L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81sJvBO1bNL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81nwJvlV3XL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81btTmzdvTL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81Ak+MMFhyL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71cw3zprscL._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "6", quantity: 8 },
          { size: "6.5", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "7.5", quantity: 2 },
          { size: "8", quantity: 12 },
          { size: "8.5", quantity: 3 },
          { size: "9", quantity: 5 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "lightblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/81F-uGaP36L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81fgqhk+dDL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/816UCqHfBLL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71j7+7fqEqL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81cxnYk2e4L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71rfNA147tL._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "5.5", quantity: 4 },
          { size: "6", quantity: 2 },
          { size: "6.5", quantity: 1 },
          { size: "7.5", quantity: 2 },
          { size: "8", quantity: 12 },
          { size: "8.5", quantity: 3 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 3,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Sole material: Rubber",
      "Outer material: #N/A",
      "Closure type: Lace-Up",
    ],
    features: [
      "The plush, supersoft upper hugs your foot and provides comfort.",
      "Grooves in the outsole allow for optimal foot flexibility and help you move freely when running the gamut.",
      "Low stack heights offer an enhanced lightweight design yet still provides the stability and support you need.",
      "Stay steady and keep progressing toward your running goals in the Flex Experience 12. Minimal with full range of motion from heel to toe, it’s made to move with every stride, pace and kick when you find your groove.",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: true,
    salePrice: 70,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "nike",
    name: "flex experience 12",
    price: 120.99,
    colors: ["black"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "11", "12"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71ficy9KZHL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/717thWpPVML._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71CwEEpltML._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71VFXsVXN2L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71BjhglB1JL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/712HOkzaz-L._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 8 },
          { size: "7.5", quantity: 10 },
          { size: "8", quantity: 15 },
          { size: "8.5", quantity: 2 },
          { size: "9", quantity: 12 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 5 },
          { size: "11", quantity: 2 },
          { size: "12", quantity: 6 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 3,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Sole material: Rubber",
      "Outer material: #N/A",
      "Closure type: Lace-Up",
    ],
    features: [
      "The plush, supersoft upper hugs your foot and provides comfort.",
      "Grooves in the outsole allow for optimal foot flexibility and help you move freely when running the gamut.",
      "Low stack heights offer an enhanced lightweight design yet still provides the stability and support you need.",
      "Stay steady and keep progressing toward your running goals in the Flex Experience 12. Minimal with full range of motion from heel to toe, it’s made to move with every stride, pace and kick when you find your groove.",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 70,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "training",
    brand: "under armour",
    name: "project rock 4",
    price: 100,
    colors: ["beige"],
    sizes: ["5", "5.5", "6", "7", "8", "9"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51O7ReLG0gL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51oUeeBiY2L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51sZgG3dnpL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61rsXZUFapL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/616ELsVBhkL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 7 },
          { size: "5.5", quantity: 5 },
          { size: "6", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "8", quantity: 20 },
          { size: "9", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Updated perforated mesh upper provides durable ventilation",
      "Strap & heel overlays for improved lockdown",
      "Bootie design for superior fit, comfort & security",
      "Charged Cushioning midsole absorbs impact & converts it into a responsive burst",
      "UA TriBase maximizes ground contact, promotes natural motion & provides flexibility to grip during lifts",
      "Full rubber outsole for elevated traction & durability",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 82,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "training",
    brand: "under armour",
    name: "project rock 4",
    price: 134.99,
    colors: ["black"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61YuZDquU-L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61ny-1YU-sL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71dAdzUqMoL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61lcO4MAqHL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61sk4amyxfL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 7 },
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 10 },
          { size: "8.5", quantity: 15 },
          { size: "9", quantity: 20 },
          { size: "9.5", quantity: 5 },
          { size: "10", quantity: 15 },
          { size: "10.5", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Updated perforated mesh upper provides durable ventilation",
      "Strap & heel overlays for improved lockdown",
      "Bootie design for superior fit, comfort & security",
      "Charged Cushioning midsole absorbs impact & converts it into a responsive burst",
      "UA TriBase maximizes ground contact, promotes natural motion & provides flexibility to grip during lifts",
      "Full rubber outsole for elevated traction & durability",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "training",
    brand: "adidas",
    name: "everyset",
    price: 90,
    colors: ["green", "darkblue"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "green",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71praFdYsuL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71RwNB8BnZL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71wVlTXM4DL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71Zz6MEAvFL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71Y0j0+N+hL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71WaSHy0s6L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 7 },
          { size: "5.5", quantity: 12 },
          { size: "6", quantity: 18 },
          { size: "6.5", quantity: 9 },
          { size: "7", quantity: 4 },
          { size: "7.5", quantity: 11 },
          { size: "8", quantity: 5 },
          { size: "8.5", quantity: 1 },
          { size: "9", quantity: 4 },
          { size: "9.5", quantity: 8 },
          { size: "10", quantity: 10 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/712AcEixHDL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71f2p6ONGEL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81YoEzOMTiL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/61unBGpbSEL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71SYXre9niL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71oDKaQ7mXL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/91df532Aq1L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5.5", quantity: 8 },
          { size: "6", quantity: 10 },
          { size: "7", quantity: 8 },
          { size: "7.5", quantity: 12 },
          { size: "9", quantity: 2 },
          { size: "9.5", quantity: 6 },
          { size: "10", quantity: 7 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Training shoes provide excellent comfort for those long gym sessions",
      "SNUG FIT: Adjustable laces provide a secure fit",
      "LIGHTWEIGHT CUSHIONING: Dual-density EVA midsole offers step-absorbing, durable comfort",
      "RUBBER OUTSOLE: The rubber outsole provides outstanding grip and a sleek, low-profile look",
      "MADE IN PART WITH RECYCLED CONTENT: This product features at least 20% recycled materials. By reusing materials that have already been created, we help to reduce waste and our reliance on finite resources and reduce the footprint of the products we make",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 54,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "adidas",
    name: "adizero",
    price: 120,
    colors: ["darkblue"],
    sizes: ["5", "5.5", "6", "7", "8", "9"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61uSf-0MJzL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71MWaO96GPL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71JOHguQstL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Oqtf4FsAL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61pLpVjZDBL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 10 },
          { size: "5.5", quantity: 10 },
          { size: "6", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "8", quantity: 20 },
          { size: "9", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: ["adidas adult Skate Shoe"],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 66.25,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "climbing",
    brand: "red chili",
    name: "clue",
    price: 123.71,
    colors: ["black"],
    sizes: ["8.5", "9", "9.5", "10", "11", "12", "12.5", "13"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51VfSQJW5nL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61VWPSijCaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51a5GZAwFYL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/5168Za8bN9L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/41NYG54DCSL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51qJt124toL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51IMVhBd3YL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "8.5", quantity: 8 },
          { size: "9", quantity: 10 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 1 },
          { size: "11", quantity: 1 },
          { size: "11.5", quantity: 5 },
          { size: "12", quantity: 8 },
          { size: "12.5", quantity: 2 },
          { size: "13", quantity: 4 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: ["Sole material Rubber", "Closure type Buckle"],
    features: [
      "Upper Material: synthetic",
      "Closure: hook-and-loop",
      "Midsole: RC-Sense",
      "Rubber: Vibram XS Grip",
      "Asymmetrical Curvature: moderate",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "climbing",
    brand: "scarpa",
    name: "arpia v",
    price: 168.95,
    colors: ["black"],
    sizes: [
      "6.5",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71lASFnzfoL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71+HrjLecmL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71ifXosRumL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71CSyDeneDL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Ogv3PJxyL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "6.5", quantity: 8 },
          { size: "7", quantity: 8 },
          { size: "8", quantity: 8 },
          { size: "8.5", quantity: 8 },
          { size: "9", quantity: 10 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 1 },
          { size: "11", quantity: 1 },
          { size: "11.5", quantity: 5 },
          { size: "12", quantity: 8 },
          { size: "12.5", quantity: 2 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: ["Sole material Rubber", "Closure type Hook & Loop"],
    features: [
      "EU Size: 39 - US Size: 7.5 Women/6.5 Men | Spot On | Precise climbing shoe balances comfort with performance for challenging routes and boulders inside and outside.",
      "Slightly Downturned | More curved than flat shoes but not as sharp as most downturned shoes for the perfect balance of comfort and performance.",
      "Vibram XS Grip 2 | Softer rubber compound gives a good grip on plastic and rock.",
      "Microsuede Upper | Strong synthetic upper fastened by two hook-and-loop straps and finished with a rubber toe cap for reduced stretch and excellent toe-hooking.",
      "Sizing Advice – Synthetic climbing shoes should fit snugly and will not stretch much over time. An ideal fit should have no dead space out of the box. Use the sizing chart in the product images or description to find your size, then downsize ½ to 1 size for premium performance.",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 138,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "hiking",
    brand: "salomon",
    name: "outpulse goretex",
    price: 121.42,
    colors: ["grey"],
    sizes: ["7", "7.5", "8.5"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "grey",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71NRA5y7qIL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71MRlqA4kRL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71IfuVEXClL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61u+hYCGw2L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61dw8IwP03L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71oQOo9xM1L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/718wbtEcOQL._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 5 },
          { size: "7.5", quantity: 2 },
          { size: "8.5", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Nylon",
      "Closure type Lace-Up",
    ],
    features: [
      "Energy Blade Outdoor: Engineered into the forefoot area of the bottom unit, Energy Blade is a lightweight TPU plate works in cohesion with the soft and springy midsole to filter the ground and deliver a smooth, dynamic stride.",
      "Fuze Surge: Made up of one of our softest EVA compounds and 30% natural rubber, Fuze Surge foam is pillowy for instant comfort and responsive enough to keep rebound levels high. Engineered using less artificial polymers, this midsole compound delivers a more earth-conscious, smooth yet dynamic stride.",
      "Reverse Camber: Inspired by Salomon's ski heritage, this curved midsole geometry helps you feel like you are floating over the ground.",
      "TOMORROW IS YOURS: Whether you are into trail running, hiking, backpacking, or mountaineering, Salomon has shoes and gear for kids, men and women to help you conquer a new distance, personal record, or event",
      "SINCE 1947 Salomon has created innovative outdoor sports gear; From running and hiking to backpacking, skiing and more, our shoes, boots, bags, apparel and accessories help make any path your own",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 92,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "salomon",
    name: "scene ride 5",
    price: 106.15,
    colors: ["blue"],
    sizes: ["10.5", "13"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "blue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/81ftdI4AaaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81uLAFiPU3L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/815fEEpokvL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81oI7WF0mNL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71njuJyUmLL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/91pGuMulLeL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "10.5", quantity: 12 },
          { size: "13", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Sole material Polyurethane",
      "Shaft height Ankle",
      "Outer material Canvas",
      "Inner material Synthetic",
    ],
    features: ["The super versatile trail running shoe for all uses"],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 92,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "hiking",
    brand: "salomon",
    name: "elixir active gtx",
    price: 155,
    colors: ["black"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61FzDysiHUL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71mb2Bl8PaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61xsloS+CfL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51h6HgP2VwL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61OXIkq3CGL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61ja61zwrmL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 12 },
          { size: "7.5", quantity: 12 },
          { size: "8", quantity: 12 },
          { size: "8.5", quantity: 12 },
          { size: "9", quantity: 12 },
          { size: "9.5", quantity: 12 },
          { size: "10", quantity: 12 },
          { size: "10.5", quantity: 12 },
          { size: "11", quantity: 12 },
          { size: "11.5", quantity: 12 },
          { size: "12", quantity: 12 },
          { size: "12.5", quantity: 12 },
          { size: "13", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Sole material Polyurethane",
      "Shaft height Ankle",
      "Outer material Canvas",
      "Inner material Synthetic",
    ],
    features: ["The super versatile trail running shoe for all uses"],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 112,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "nike",
    name: "downshifter",
    price: 79,
    colors: ["lightblue"],
    sizes: ["5", "5.5", "8", "8.5", "9", "9.5", "10", "11", "12"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "lightblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/81tVT-ssU2L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81hWsvC7gOL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71zVcjATZbL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71QKaxKe74L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81hSf7L-rIL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81XdppRuhZL._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 8 },
          { size: "5.5", quantity: 10 },
          { size: "8", quantity: 15 },
          { size: "8.5", quantity: 2 },
          { size: "9", quantity: 12 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 5 },
          { size: "11", quantity: 2 },
          { size: "12", quantity: 6 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 3,
        date: "2024-12-15",
      },
    ],
    details: [
      "Sole material: Rubber",
      "Outer material: Mesh",
      "Closure type: Lace-Up",
      "Water resistance level: Not Water Resistant",
    ],
    features: ["Rubber sole"],
    realeaseDate: "02-11-2024",
    featured: false,
    sale: true,
    salePrice: 54,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "new balance",
    name: "fresh foam x 880",
    price: 114.95,
    colors: ["black", "orange", "blue"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61LGqMZ5UXL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61jI0ayfZeL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61vD+GAr9oL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61-GCPoP75L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61lz0VJRDOL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71lU-fAtEXL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 8 },
          { size: "7.5", quantity: 10 },
          { size: "8", quantity: 15 },
          { size: "8.5", quantity: 2 },
          { size: "9", quantity: 12 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 5 },
          { size: "10.5", quantity: 2 },
          { size: "11", quantity: 6 },
          { size: "11.5", quantity: 2 },
          { size: "12", quantity: 6 },
          { size: "12.5", quantity: 2 },
          { size: "13", quantity: 6 },
          { size: "14", quantity: 2 },
          { size: "15", quantity: 6 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "orange",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71TMgBPHJFL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/714Dh9mpHcL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/714MRYyVStL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71HaN9SZaWL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/612+7k2aQAL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71Uvn18ChGL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 10 },
          { size: "10.5", quantity: 5 },
          { size: "11.5", quantity: 5 },
          { size: "12.5", quantity: 5 },
          { size: "13", quantity: 5 },
          { size: "14", quantity: 5 },
          { size: "15", quantity: 5 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "blue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71kpXP8p3SL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/718In2BmkyL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71ar0vcgZwL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71NuDQV2SlL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61hiNHyVwaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/714gIZwrG-L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "11", quantity: 2 },
          { size: "12", quantity: 6 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 3,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Origin: Imported",
      "Sole material: Rubber",
      "Outer material: Synthetic and Mesh",
    ],
    features: [
      "Fresh Foam X midsole foam with approximately 3% bio-based content delivers our most cushioned Fresh Foam experience for incredible comfort.",
      "Neutral cushioning – for runners who do not require additional stability",
      "Breathable synthetic and mesh upper",
      "Structured and supportive upper design",
      "8 mm drop; due to variances created during the development and manufacturing processes, all references to 8 mm drop are approximate",
    ],
    realeaseDate: "02-11-2024",
    featured: true,
    sale: false,
    salePrice: 99.62,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "new balance",
    name: "fresh foam x 880",
    price: 139.99,
    colors: ["lightblue", "lightgreen", "orange"],
    sizes: [
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "lightblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51o1onb4djL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51M6NgQBmhL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/513u06YgdUL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Iiz3mNZML._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71ZUDauanRL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51NmoERaG1L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51tL3GKKEVL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 8 },
          { size: "5.5", quantity: 8 },
          { size: "6", quantity: 8 },
          { size: "6.5", quantity: 8 },
          { size: "7", quantity: 8 },
          { size: "7.5", quantity: 10 },
          { size: "8", quantity: 15 },
          { size: "8.5", quantity: 2 },
          { size: "9", quantity: 12 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 5 },
          { size: "11", quantity: 6 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "lightgreen",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51bfzTuf2cL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51Xm87WBX1L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51OeG91-ThL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61uea5RnOFL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61LDgzNp5mL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51Cbm0TzXXL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51cZe0QGFpL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 18 },
          { size: "5.5", quantity: 3 },
          { size: "6", quantity: 4 },
          { size: "6.5", quantity: 9 },
          { size: "7", quantity: 1 },
          { size: "7.5", quantity: 4 },
          { size: "8", quantity: 5 },
          { size: "8.5", quantity: 2 },
          { size: "9", quantity: 12 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "orange",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61++XRhgaTL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51WRTVpnh0L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51N6X-0wRGL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61U2ujR0DNL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/712BDuOS69L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51viiVQvWlL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51Nk-eLMYuL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "6", quantity: 4 },
          { size: "6.5", quantity: 9 },
          { size: "8", quantity: 5 },
          { size: "11", quantity: 2 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 3,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Origin: Imported",
      "Sole material: Rubber",
      "Outer material: Synthetic and Mesh",
    ],
    features: [
      "Fresh Foam X midsole foam with approximately 3% bio-based content delivers our most cushioned Fresh Foam experience for incredible comfort.",
      "Neutral cushioning – for runners who do not require additional stability",
      "Breathable synthetic and mesh upper",
      "Structured and supportive upper design",
      "8 mm drop; due to variances created during the development and manufacturing processes, all references to 8 mm drop are approximate",
    ],
    realeaseDate: "02-11-2024",
    featured: true,
    sale: true,
    salePrice: 104.95,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "asics",
    name: "gt 200",
    price: 159.99,
    colors: ["grey", "darkblue"],
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "grey",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61ypAGRjtuL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61iJi1s-zOL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61+nhDdpy3L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61CS9Mf5hUL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61G1b8uuKSL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Un5oeEwEL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/615WNTLP+-L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "6", quantity: 18 },
          { size: "6.5", quantity: 6 },
          { size: "7", quantity: 16 },
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 6 },
          { size: "8.5", quantity: 4 },
          { size: "9", quantity: 9 },
          { size: "9.5", quantity: 16 },
          { size: "10", quantity: 6 },
          { size: "10.5", quantity: 5 },
          { size: "11", quantity: 5 },
          { size: "11.5", quantity: 15 },
          { size: "12", quantity: 12 },
          { size: "12.5", quantity: 12 },
          { size: "13", quantity: 6 },
          { size: "14", quantity: 8 },
          { size: "15", quantity: 5 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61Gc7Ir0WWL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61+xLdrYYaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Z4MFDAgoL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61JxUWJJ2DL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61q0gc5GgwL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61o6uPdrTrL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71dJFA0MvmL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 16 },
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 6 },
          { size: "8.5", quantity: 4 },
          { size: "9", quantity: 9 },
          { size: "9.5", quantity: 16 },
          { size: "10", quantity: 6 },
          { size: "10.5", quantity: 5 },
          { size: "11", quantity: 5 },
          { size: "11.5", quantity: 15 },
          { size: "12", quantity: 12 },
          { size: "12.5", quantity: 12 },
          { size: "13", quantity: 6 },
          { size: "14", quantity: 8 },
          { size: "15", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user4",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 5,
        date: "2024-12-17",
      },
    ],
    details: [
      "Origin: Imported",
      "Sole material: Rubber",
      "Outer material: Polyester",
      "Closure type: Lace-Up",
    ],
    features: [
      "Jacquard mesh upper: Offers a supportive and comfortable foothold",
      "At least 50% of the shoe's main upper material is made with recycled content to reduce waste and carbon emissions:",
      "The sockliner is produced with the solution dyeing process that reduces water usage by approximately 33% and carbon emissions by approximately 45% compared to the conventional dyeing technology:",
      "3D GUIDANCE SYSTEM: Helps provide advanced stability for a smoother stride",
      "Rearfoot PureGEL technology: Helps provide lightweight cushioning and softer landings",
    ],
    realeaseDate: "02-11-2024",
    featured: true,
    sale: false,
    salePrice: 114.55,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "asics",
    name: "gt 200",
    price: 159.99,
    colors: ["black"],
    sizes: [
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
      "15",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61e76rzIRLL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61rSiM17g+L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61PPSb4XKuL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51z3hjNe5lL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51jRoupgyhL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61YTDRzf-7L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71uEuvb6B9L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 6 },
          { size: "8.5", quantity: 4 },
          { size: "9", quantity: 9 },
          { size: "9.5", quantity: 16 },
          { size: "10", quantity: 6 },
          { size: "10.5", quantity: 5 },
          { size: "11", quantity: 5 },
          { size: "11.5", quantity: 15 },
          { size: "12", quantity: 12 },
          { size: "12.5", quantity: 12 },
          { size: "13", quantity: 6 },
          { size: "14", quantity: 8 },
          { size: "15", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user4",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 5,
        date: "2024-12-17",
      },
    ],
    details: [
      "Origin: Imported",
      "Sole material: Rubber",
      "Outer material: Polyester",
      "Closure type: Lace-Up",
    ],
    features: [
      "Jacquard mesh upper: Offers a supportive and comfortable foothold",
      "At least 50% of the shoe's main upper material is made with recycled content to reduce waste and carbon emissions:",
      "The sockliner is produced with the solution dyeing process that reduces water usage by approximately 33% and carbon emissions by approximately 45% compared to the conventional dyeing technology:",
      "3D GUIDANCE SYSTEM: Helps provide advanced stability for a smoother stride",
      "Rearfoot PureGEL technology: Helps provide lightweight cushioning and softer landings",
    ],
    realeaseDate: "02-11-2024",
    featured: false,
    sale: false,
    salePrice: 114.55,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "on",
    name: "cloudswift 3",
    price: 129.3,
    colors: ["darkblue"],
    sizes: ["6", "6.5", "7", "7.5", "8", "9", "9.5"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51sJs0z5poL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51ExaBG-ecL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51-1CgzNDsL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51zNechGPFL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "6", quantity: 15 },
          { size: "6.5", quantity: 10 },
          { size: "7", quantity: 4 },
          { size: "7.5", quantity: 9 },
          { size: "8", quantity: 3 },
          { size: "9", quantity: 4 },
          { size: "9.5", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 4,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions Machine Wash",
      "Origin Imported",
      "Sole material Rubber",
      "Outer materialPolyester",
    ],
    features: [
      "Fabric: Performance knit",
      "Rubber sole",
      "Reflective logo details, Integrated collar and tongue, Removable insole, Designed for running",
    ],
    realeaseDate: "02-01-2025",
    featured: false,
    sale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "on",
    name: "cloudnova form 2",
    price: 239.95,
    colors: ["black"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51jJN90wXvL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51jOK4WBmhL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/513eO4t1MeL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51jB0wrhe4L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51e9GuxTomL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51ka-nDOYuL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61rsCxZa4PL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 15 },
          { size: "7.5", quantity: 10 },
          { size: "8", quantity: 4 },
          { size: "8.5", quantity: 9 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 4 },
          { size: "10", quantity: 5 },
          { size: "10.5", quantity: 15 },
          { size: "11", quantity: 15 },
          { size: "11.5", quantity: 15 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 4,
        date: "2024-12-15",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Rubber sole",
      "Designed for everyday wear, Reflective accents, Lightweight design, Patented CloudTec sole",
      "Round toe",
    ],
    realeaseDate: "02-01-2025",
    featured: false,
    sale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "on",
    name: "cloud 5",
    price: 180.43,
    colors: ["orange"],
    sizes: [
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "orange",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61fYfCMeq+L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Gl-yytYAL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61V70rrfWPL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61O7+uYoRjL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5.5", quantity: 15 },
          { size: "6", quantity: 15 },
          { size: "6.5", quantity: 15 },
          { size: "7", quantity: 15 },
          { size: "7.5", quantity: 10 },
          { size: "8", quantity: 4 },
          { size: "8.5", quantity: 9 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 4 },
          { size: "10", quantity: 5 },
          { size: "10.5", quantity: 15 },
          { size: "11", quantity: 15 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "OriginImported",
      "Sole materialRubber",
      "Outer materialPolyester",
      "Inner materialFabric",
    ],
    features: [
      "Rubber sole",
      "Reflective logo details, Patented CloudTec sole, Removable insole, Cushioned collar and tongue, Lightweight design, Designed for everyday wear",
    ],
    realeaseDate: "02-01-2025",
    featured: false,
    sale: false,
    salePrice: 133.12,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "altra",
    name: "escalante 4",
    price: 222,
    colors: ["green", "black", "teal"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
      "14",
      "15",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "green",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61UnHJY05sL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61z8BLfqAVL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/715dodhZqIL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/616wbHoeqZL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/713mtuNxvtL._AC_SY695_.jpg",
        ],
        sizes: [{ size: "7", quantity: 5 }],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61j7EuCXlTL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61cArDwncDL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71aVy4RzU1L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71MSiVRC9UL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61NwXGvUrHL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 15 },
          { size: "7.5", quantity: 15 },
          { size: "8", quantity: 15 },
          { size: "8.5", quantity: 15 },
          { size: "9", quantity: 15 },
          { size: "9.5", quantity: 15 },
          { size: "10", quantity: 15 },
          { size: "10.5", quantity: 15 },
          { size: "11", quantity: 15 },
          { size: "11.5", quantity: 15 },
          { size: "12", quantity: 15 },
          { size: "13", quantity: 15 },
          { size: "14", quantity: 15 },
          { size: "15", quantity: 15 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "teal",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/41ymD+LuOrL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/41mOs2znX9L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/5152toWindL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/41Rxf+E8qTL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/41Iyic9YPOL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 15 },
          { size: "7.5", quantity: 15 },
          { size: "8", quantity: 15 },
          { size: "8.5", quantity: 15 },
          { size: "9", quantity: 15 },
          { size: "9.5", quantity: 15 },
          { size: "10", quantity: 15 },
          { size: "10.5", quantity: 15 },
          { size: "11", quantity: 15 },
          { size: "11.5", quantity: 15 },
          { size: "12", quantity: 15 },
          { size: "12.5", quantity: 15 },
          { size: "13", quantity: 15 },
          { size: "14", quantity: 15 },
          { size: "15", quantity: 15 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Origin: Imported",
      "Sole material: Rubber",
      "Outer material: Mesh",
      "Closure type: Lace-Up",
    ],
    features: [
      "Go Further: Our original Altra EGO foam is designed to provide added energy return and a responsive, yet soft, comfortable feel.",
      "To The MAX: Our Altra EGO MAX midsole foam gives you all the light and luxurious performance with a little extra bounce and added durability.",
      "Get Comfortable: Signature Altra Balanced Cushioning and FootShape toe boxes allow your toes to spread and encourages proper, low-impact form throughout your run",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 129.95,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "hiking",
    brand: "altra",
    name: "lone peak 7",
    price: 143.33,
    colors: ["grey", "teal", "darkblue"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
      "14",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "grey",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71GJG9lGBZL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/718ipH7kxKL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71u8kzIalIL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61IXb7J4t5L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71LAjFbxMxL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 5 },
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 5 },
          { size: "8.5", quantity: 5 },
          { size: "9", quantity: 5 },
          { size: "9.5", quantity: 5 },
          { size: "10", quantity: 5 },
          { size: "10.5", quantity: 5 },
          { size: "11", quantity: 5 },
          { size: "11.5", quantity: 5 },
          { size: "12", quantity: 5 },
          { size: "12.5", quantity: 5 },
          { size: "13", quantity: 5 },
          { size: "14", quantity: 5 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "teal",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/619RADORCtL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71rXLYawhyL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71sHYLmlHSL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/612c17u7ITL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71enFkLZLxL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 5 },
          { size: "8.5", quantity: 5 },
          { size: "9", quantity: 5 },
          { size: "9.5", quantity: 5 },
          { size: "10", quantity: 5 },
          { size: "10.5", quantity: 5 },
          { size: "11", quantity: 5 },
          { size: "11.5", quantity: 5 },
          { size: "12", quantity: 5 },
          { size: "12.5", quantity: 5 },
          { size: "13", quantity: 5 },
          { size: "14", quantity: 5 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61rLN+MZpbL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71zjSoqnH6L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71YE2MVn8CL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61bhJraqYGL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71m9jnxmZGL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 5 },
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 5 },
          { size: "8.5", quantity: 5 },
          { size: "9", quantity: 5 },
          { size: "9.5", quantity: 5 },
          { size: "10", quantity: 5 },
          { size: "10.5", quantity: 5 },
          { size: "11", quantity: 5 },
          { size: "11.5", quantity: 5 },
          { size: "12", quantity: 5 },
          { size: "12.5", quantity: 5 },
          { size: "13", quantity: 5 },
          { size: "14", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions Machine Wash",
      "Sole material Rubber",
      "Outer material Synthetic",
      "Closure type Lace-Up",
    ],
    features: ["Rubber sole"],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 109.31,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "salomon",
    name: "sense ride 5",
    price: 115.35,
    colors: ["beige"],
    sizes: ["5", "6", "7", "7.5", "8", "8.5"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71PSvbAPRXL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/714JV-xy-aL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/817hGvhuh6L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81VQBQEUMOL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71VPNBB7FrL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81am4Kne0yL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 5 },
          { size: "6", quantity: 5 },
          { size: "7", quantity: 5 },
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 5 },
          { size: "8.5", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Origin: Imported",
      "Sole material: Rubber",
      "Outer material: Mesh",
    ],
    features: [
      "FOR: Versatile women’s trail running shoe equally in its element on short, fast trail runs and hiking as it is on ultra distances, this super comfortable overachieving trail runner easily adapts to a variety of terrains, with a balanced midsole for cushioning and adaptive response, premium traction and an engineered mesh upper featuring Sensifit for just the right amount of comfortable hold. Predecessor Sense Ride 4.",
      "VERSATILE GRIP: All-terrain Contagrip outsole with 3.5 mm lugs for premium adhesion/traction with confidence. Ideal for navigating diverse terrain, including rocky trails, muddy paths, and loose gravel on a wide range of outdoor trail terrain.",
      "SECURE FIT: Featuring Sensifit construction and a Quicklace single pull and stowable lace closure for a precise optimal foothold, and welded, foot-hugging comfort.",
      "CUSHION & RESPONSE: Energy sole midsole cushioning provides the right balance of cushioning and adaptive response.",
    ],
    realeaseDate: "02-01-2025",
    featured: false,
    sale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "salomon",
    name: "sense ride 5",
    price: 115.35,
    colors: ["grey", "beige"],
    sizes: ["8.5", "9.5", "10", "11.5", "12.5"],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "grey",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51CBDL7xOOL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51CBDL7xOOL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "8.5", quantity: 3 },
          { size: "11.5", quantity: 2 },
          { size: "12.5", quantity: 7 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/71I3vB6eFGL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71H8M5m5peL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81zxV1ZDK8L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/819riJjHqLL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71bnnqPTgzL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "9.5", quantity: 2 },
          { size: "10", quantity: 6 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Origin: Imported",
      "Sole material: Rubber",
      "Outer material: Mesh",
    ],
    features: [
      "FOR: Versatile women’s trail running shoe equally in its element on short, fast trail runs and hiking as it is on ultra distances, this super comfortable overachieving trail runner easily adapts to a variety of terrains, with a balanced midsole for cushioning and adaptive response, premium traction and an engineered mesh upper featuring Sensifit for just the right amount of comfortable hold. Predecessor Sense Ride 4.",
      "VERSATILE GRIP: All-terrain Contagrip outsole with 3.5 mm lugs for premium adhesion/traction with confidence. Ideal for navigating diverse terrain, including rocky trails, muddy paths, and loose gravel on a wide range of outdoor trail terrain.",
      "SECURE FIT: Featuring Sensifit construction and a Quicklace single pull and stowable lace closure for a precise optimal foothold, and welded, foot-hugging comfort.",
      "CUSHION & RESPONSE: Energy sole midsole cushioning provides the right balance of cushioning and adaptive response.",
    ],
    realeaseDate: "02-01-2025",
    featured: false,
    sale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "salomon",
    name: "sense ride 4",
    price: 130,
    colors: ["lightblue", "black"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "lightblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/814A4sz2VkL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81aulaKDvlL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81coXUpstIL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71jIIv6-NqL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81oPft07fkL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 3 },
          { size: "7.5", quantity: 3 },
          { size: "8", quantity: 3 },
          { size: "8.5", quantity: 3 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 3 },
          { size: "10.5", quantity: 3 },
          { size: "11", quantity: 3 },
          { size: "11.5", quantity: 3 },
          { size: "12", quantity: 3 },
          { size: "12.5", quantity: 3 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/815W1+7FRWS._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81iAhheCMtS._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81ip7PUkX+S._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/61JeRW4fUvS._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71X+bVAta2S._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71rhbwRbcYS._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 3 },
          { size: "7.5", quantity: 3 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 3 },
          { size: "10.5", quantity: 3 },
          { size: "11", quantity: 3 },
          { size: "11.5", quantity: 3 },
          { size: "12", quantity: 3 },
          { size: "12.5", quantity: 3 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Fabric type: LINING Textile OUTSOLE Rubber UPPER Textile/Synthetic",
      "Care instructions: Machine Wash",
      "Sole material: Rubber",
      "Outer material: Textile/Synthetic",
    ],
    features: [
      "Trail Running Shoes: The Salomon Sense Ride 4 combines Optivibe cushioning to absorb shock and decrease muscle fatigue with trail specific features like anti debris mesh, a breathable upper, and a grippy outsole",
      "Go All Day Everyday: The Sense Ride 4 combines the cushioning of road running shoes with extra grip and protection; Take on any trail with a Contagrip outsole and Profeel film to protect feet from sharp objects",
      "Go The Distance: Whether you love road running in your neighborhood, an escape to a local trail, or something more rugged, Salomon makes shoes that ensure you have a smooth ride on any and all terrain",
      "TOMORROW IS YOURS: Whether you are into trail running, hiking, backpacking, or mountaineering, Salomon has shoes and gear for kids, men and women to help you conquer a new distance, personal record, or event",
      "SINCE 1947 Salomon has created innovative outdoor sports gear; From running and hiking to backpacking, skiing and more, our shoes, boots, bags, apparel and accessories help make any path your own",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 95,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "saucony",
    name: "ride 17",
    price: 160,
    colors: ["white", "darkblue"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "white",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/81bIDJXsj2L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81gT88V4hIL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81+fx8ZIxrL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81lQIxFoRyL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/91nD6aL-wHL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81uL4O3SJVL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 3 },
          { size: "7.5", quantity: 3 },
          { size: "8", quantity: 3 },
          { size: "8.5", quantity: 3 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 3 },
          { size: "10.5", quantity: 3 },
          { size: "11", quantity: 3 },
          { size: "11.5", quantity: 3 },
          { size: "12", quantity: 3 },
          { size: "12.5", quantity: 3 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/51ARda51QlL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51Ku1MQ-6NL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51Bx+AKODHL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51j-U2TUQAL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61xnhKWzf9L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51lTfVViQ8L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 3 },
          { size: "7.5", quantity: 3 },
          { size: "8", quantity: 3 },
          { size: "8.5", quantity: 3 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 3 },
          { size: "10.5", quantity: 3 },
          { size: "11", quantity: 3 },
          { size: "11.5", quantity: 3 },
          { size: "12", quantity: 3 },
          { size: "12.5", quantity: 3 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Origin: Imported",
      "Sole material: Synthetic Rubber",
      "Outer material: Mesh",
    ],
    features: [
      "PWRRUN+ cushioning offers supreme comfort and puts a spring to your daily movement",
      "Engineered mesh design offers more breathability across the toes, improved midfoot wrap, and locked down comfort in the heal",
      "Durable underfoot in high-wear contact points",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 82.66,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "saucony",
    name: "endorphin speed 4",
    price: 169.95,
    colors: ["black", "lightblue"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    images: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/61Z5VoMqtAL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/5183tXY3jGL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61MtgYT8QTL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51p8F0fOZ0L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Xip23pQqL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61jgbVstZDL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 3 },
          { size: "7.5", quantity: 3 },
          { size: "8", quantity: 3 },
          { size: "8.5", quantity: 3 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 3 },
          { size: "10.5", quantity: 3 },
          { size: "11", quantity: 3 },
          { size: "11.5", quantity: 3 },
          { size: "12", quantity: 3 },
          { size: "12.5", quantity: 3 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "lightblue",
        imagesUrl: [
          "https://m.media-amazon.com/images/I/811ai8IB6yL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81c2UH4ratL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81NoX9TPwBL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81utjmoUVkL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/911h-uSkPNL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81wZtarSNGL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 3 },
          { size: "7.5", quantity: 3 },
          { size: "8", quantity: 3 },
          { size: "8.5", quantity: 3 },
          { size: "9", quantity: 3 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 3 },
          { size: "10.5", quantity: 3 },
          { size: "11", quantity: 3 },
          { size: "11.5", quantity: 3 },
          { size: "12", quantity: 3 },
          { size: "12.5", quantity: 3 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Origin: Imported",
      "Sole material: Synthetic Rubber",
      "Outer material: Mesh",
      "Closure type: Lace-Up",
    ],
    features: [
      "Smooth SPEEDROLL technology is effortless speed and addictive forward motion you can rely on daily.",
      "Energy efficient PWRRUN PB technology features superfoam cushioning that snaps back.",
      "Improved design has zonal engineered mesh and integrated tongue for a connected, secure fit.",
      "Step into our newest SRS (Super Responsive Sockliner). We dare you not to bounce.",
      "Re-engineered Plate- Vertical reinforcement to add torsional rigidity, while maintaining flexibility through the forefoot.",
    ],
    realeaseDate: "02-01-2025",
    featured: true,
    sale: false,
    salePrice: 82.66,
  },
];
