import { v4 as uuidv4 } from "uuid";

export const SHOP_DATA = [
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "training",
    brand: "under armour",
    name: "project rock 4",
    price: 100,
    aivalableColors: ["beige"],
    sizes: ["6", "7", "8", "9"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        images: [
          "https://m.media-amazon.com/images/I/61E3yRVw9PL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51DcObHeclL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61bA8dp+aZL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71lzKr0SxBL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61qd6ftNrrL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "6", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "8", quantity: 20 },
          { size: "9", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Updated perforated mesh upper provides durable ventilation",
      "Strap & heel overlays for improved lockdown",
      "Bootie design for superior fit, comfort & security",
      "Charged Cushioning midsole absorbs impact & converts it into a responsive burst",
      "UA TriBase maximizes ground contact, promotes natural motion & provides flexibility to grip during lifts",
      "Full rubber outsole for elevated traction & durability",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 82,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "nike",
    name: "flex experience 12",
    price: 120.99,
    aivalableColors: ["beige", "lightblue"],
    sizes: ["5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        images: [
          "https://m.media-amazon.com/images/I/81-WWFBuTSL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81drd1xq72L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81sJvBO1bNL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81nwJvlV3XL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81btTmzdvTL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81Ak+MMFhyL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71cw3zprscL._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "6", quantity: 8 },
          { size: "6.5", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "7.5", quantity: 2 },
          { size: "8", quantity: 12 },
          { size: "8.5", quantity: 3 },
          { size: "9", quantity: 5 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "lightblue",
        images: [
          "https://m.media-amazon.com/images/I/81F-uGaP36L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/81fgqhk+dDL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/816UCqHfBLL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71j7+7fqEqL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81cxnYk2e4L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71rfNA147tL._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "5.5", quantity: 4 },
          { size: "6", quantity: 2 },
          { size: "6.5", quantity: 1 },
          { size: "7.5", quantity: 2 },
          { size: "8", quantity: 12 },
          { size: "8.5", quantity: 3 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 3,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Sole material: Rubber",
      "Outer material: #N/A",
      "Closure type: Lace-Up",
    ],
    features: [
      "The plush, supersoft upper hugs your foot and provides comfort.",
      "Grooves in the outsole allow for optimal foot flexibility and help you move freely when running the gamut.",
      "Low stack heights offer an enhanced lightweight design yet still provides the stability and support you need.",
      "Stay steady and keep progressing toward your running goals in the Flex Experience 12. Minimal with full range of motion from heel to toe, it’s made to move with every stride, pace and kick when you find your groove.",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 70,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "nike",
    name: "flex experience 12",
    price: 120.99,
    aivalableColors: ["black"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "11", "12"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        images: [
          "https://m.media-amazon.com/images/I/71ficy9KZHL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/717thWpPVML._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71CwEEpltML._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71VFXsVXN2L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71BjhglB1JL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/712HOkzaz-L._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 8 },
          { size: "7.5", quantity: 10 },
          { size: "8", quantity: 15 },
          { size: "8.5", quantity: 2 },
          { size: "9", quantity: 12 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 5 },
          { size: "11", quantity: 2 },
          { size: "12", quantity: 6 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
      {
        userId: "user3",
        displayName: "Jane Doe",
        reviewText: "The shoes are comfortable and fit well.",
        rating: 3,
        date: "2024-12-15",
      },
    ],
    details: [
      "Care instructions: Machine Wash",
      "Sole material: Rubber",
      "Outer material: #N/A",
      "Closure type: Lace-Up",
    ],
    features: [
      "The plush, supersoft upper hugs your foot and provides comfort.",
      "Grooves in the outsole allow for optimal foot flexibility and help you move freely when running the gamut.",
      "Low stack heights offer an enhanced lightweight design yet still provides the stability and support you need.",
      "Stay steady and keep progressing toward your running goals in the Flex Experience 12. Minimal with full range of motion from heel to toe, it’s made to move with every stride, pace and kick when you find your groove.",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 70,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "training",
    brand: "under armour",
    name: "project rock 4",
    price: 100,
    aivalableColors: ["beige"],
    sizes: ["5", "5.5", "6", "7", "8", "9"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "beige",
        images: [
          "https://m.media-amazon.com/images/I/51O7ReLG0gL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51oUeeBiY2L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51sZgG3dnpL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61rsXZUFapL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/616ELsVBhkL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 7 },
          { size: "5.5", quantity: 5 },
          { size: "6", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "8", quantity: 20 },
          { size: "9", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Updated perforated mesh upper provides durable ventilation",
      "Strap & heel overlays for improved lockdown",
      "Bootie design for superior fit, comfort & security",
      "Charged Cushioning midsole absorbs impact & converts it into a responsive burst",
      "UA TriBase maximizes ground contact, promotes natural motion & provides flexibility to grip during lifts",
      "Full rubber outsole for elevated traction & durability",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 82,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "training",
    brand: "under armour",
    name: "project rock 4",
    price: 134.99,
    aivalableColors: ["black"],
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        images: [
          "https://m.media-amazon.com/images/I/61YuZDquU-L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61ny-1YU-sL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71dAdzUqMoL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61lcO4MAqHL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61sk4amyxfL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 7 },
          { size: "7.5", quantity: 5 },
          { size: "8", quantity: 10 },
          { size: "8.5", quantity: 15 },
          { size: "9", quantity: 20 },
          { size: "9.5", quantity: 5 },
          { size: "10", quantity: 15 },
          { size: "10.5", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Updated perforated mesh upper provides durable ventilation",
      "Strap & heel overlays for improved lockdown",
      "Bootie design for superior fit, comfort & security",
      "Charged Cushioning midsole absorbs impact & converts it into a responsive burst",
      "UA TriBase maximizes ground contact, promotes natural motion & provides flexibility to grip during lifts",
      "Full rubber outsole for elevated traction & durability",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "training",
    brand: "adidas",
    name: "everyset",
    price: 90,
    aivalableColors: ["green", "darkblue"],
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "green",
        images: [
          "https://m.media-amazon.com/images/I/71praFdYsuL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71RwNB8BnZL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71wVlTXM4DL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71Zz6MEAvFL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71Y0j0+N+hL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71WaSHy0s6L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 7 },
          { size: "5.5", quantity: 12 },
          { size: "6", quantity: 18 },
          { size: "6.5", quantity: 9 },
          { size: "7", quantity: 4 },
          { size: "7.5", quantity: 11 },
          { size: "8", quantity: 5 },
          { size: "8.5", quantity: 1 },
          { size: "9", quantity: 4 },
          { size: "9.5", quantity: 8 },
          { size: "10", quantity: 10 },
        ],
      },
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        images: [
          "https://m.media-amazon.com/images/I/712AcEixHDL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71f2p6ONGEL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81YoEzOMTiL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/61unBGpbSEL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71SYXre9niL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71oDKaQ7mXL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/91df532Aq1L._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5.5", quantity: 8 },
          { size: "6", quantity: 10 },
          { size: "7", quantity: 8 },
          { size: "7.5", quantity: 12 },
          { size: "9", quantity: 2 },
          { size: "9.5", quantity: 6 },
          { size: "10", quantity: 7 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: [
      "Training shoes provide excellent comfort for those long gym sessions",
      "SNUG FIT: Adjustable laces provide a secure fit",
      "LIGHTWEIGHT CUSHIONING: Dual-density EVA midsole offers step-absorbing, durable comfort",
      "RUBBER OUTSOLE: The rubber outsole provides outstanding grip and a sleek, low-profile look",
      "MADE IN PART WITH RECYCLED CONTENT: This product features at least 20% recycled materials. By reusing materials that have already been created, we help to reduce waste and our reliance on finite resources and reduce the footprint of the products we make",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 54,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "running",
    brand: "adidas",
    name: "adizero",
    price: 120,
    aivalableColors: ["darkblue"],
    sizes: ["5", "5.5", "6", "7", "8", "9"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "darkblue",
        images: [
          "https://m.media-amazon.com/images/I/61uSf-0MJzL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71MWaO96GPL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71JOHguQstL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Oqtf4FsAL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61pLpVjZDBL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "5", quantity: 10 },
          { size: "5.5", quantity: 10 },
          { size: "6", quantity: 10 },
          { size: "7", quantity: 15 },
          { size: "8", quantity: 20 },
          { size: "9", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Polyester",
      "Closure type Lace-Up",
    ],
    features: ["adidas adult Skate Shoe"],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 66.25,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "climbing",
    brand: "red chili",
    name: "clue",
    price: 123.71,
    aivalableColors: ["black"],
    sizes: ["8.5", "9", "9.5", "10", "11", "12", "12.5", "13"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        images: [
          "https://m.media-amazon.com/images/I/51VfSQJW5nL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61VWPSijCaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51a5GZAwFYL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/5168Za8bN9L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/41NYG54DCSL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51qJt124toL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51IMVhBd3YL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "8.5", quantity: 8 },
          { size: "9", quantity: 10 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 1 },
          { size: "11", quantity: 1 },
          { size: "11.5", quantity: 5 },
          { size: "12", quantity: 8 },
          { size: "12.5", quantity: 2 },
          { size: "13", quantity: 4 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: ["Sole material Rubber", "Closure type Buckle"],
    features: [
      "Upper Material: synthetic",
      "Closure: hook-and-loop",
      "Midsole: RC-Sense",
      "Rubber: Vibram XS Grip",
      "Asymmetrical Curvature: moderate",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 100,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "women",
    sport: "climbing",
    brand: "scarpa",
    name: "arpia v",
    price: 168.95,
    aivalableColors: ["black"],
    sizes: [
      "6.5",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "11",
      "11.5",
      "12",
      "12.5",
    ],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        images: [
          "https://m.media-amazon.com/images/I/71lASFnzfoL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71+HrjLecmL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71ifXosRumL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71CSyDeneDL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61Ogv3PJxyL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "6.5", quantity: 8 },
          { size: "7", quantity: 8 },
          { size: "8", quantity: 8 },
          { size: "8.5", quantity: 8 },
          { size: "9", quantity: 10 },
          { size: "9.5", quantity: 3 },
          { size: "10", quantity: 1 },
          { size: "11", quantity: 1 },
          { size: "11.5", quantity: 5 },
          { size: "12", quantity: 8 },
          { size: "12.5", quantity: 2 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: ["Sole material Rubber", "Closure type Hook & Loop"],
    features: [
      "EU Size: 39 - US Size: 7.5 Women/6.5 Men | Spot On | Precise climbing shoe balances comfort with performance for challenging routes and boulders inside and outside.",
      "Slightly Downturned | More curved than flat shoes but not as sharp as most downturned shoes for the perfect balance of comfort and performance.",
      "Vibram XS Grip 2 | Softer rubber compound gives a good grip on plastic and rock.",
      "Microsuede Upper | Strong synthetic upper fastened by two hook-and-loop straps and finished with a rubber toe cap for reduced stretch and excellent toe-hooking.",
      "Sizing Advice – Synthetic climbing shoes should fit snugly and will not stretch much over time. An ideal fit should have no dead space out of the box. Use the sizing chart in the product images or description to find your size, then downsize ½ to 1 size for premium performance.",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 138,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "hiking",
    brand: "salomon",
    name: "outpulse goretex",
    price: 121.42,
    aivalableColors: ["grey"],
    sizes: ["7", "7.5", "8.5"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "grey",
        images: [
          "https://m.media-amazon.com/images/I/71NRA5y7qIL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71MRlqA4kRL._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71IfuVEXClL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61u+hYCGw2L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61dw8IwP03L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/71oQOo9xM1L._AC_SX695_.jpg",
          "https://m.media-amazon.com/images/I/718wbtEcOQL._AC_SX695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 5 },
          { size: "7.5", quantity: 2 },
          { size: "8.5", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Origin Imported",
      "Sole material Rubber",
      "Outer material Nylon",
      "Closure type Lace-Up",
    ],
    features: [
      "Energy Blade Outdoor: Engineered into the forefoot area of the bottom unit, Energy Blade is a lightweight TPU plate works in cohesion with the soft and springy midsole to filter the ground and deliver a smooth, dynamic stride.",
      "Fuze Surge: Made up of one of our softest EVA compounds and 30% natural rubber, Fuze Surge foam is pillowy for instant comfort and responsive enough to keep rebound levels high. Engineered using less artificial polymers, this midsole compound delivers a more earth-conscious, smooth yet dynamic stride.",
      "Reverse Camber: Inspired by Salomon's ski heritage, this curved midsole geometry helps you feel like you are floating over the ground.",
      "TOMORROW IS YOURS: Whether you are into trail running, hiking, backpacking, or mountaineering, Salomon has shoes and gear for kids, men and women to help you conquer a new distance, personal record, or event",
      "SINCE 1947 Salomon has created innovative outdoor sports gear; From running and hiking to backpacking, skiing and more, our shoes, boots, bags, apparel and accessories help make any path your own",
    ],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 92,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "running",
    brand: "salomon",
    name: "scene ride 5",
    price: 106.15,
    aivalableColors: ["blue"],
    sizes: ["10.5", "13"],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "blue",
        images: [
          "https://m.media-amazon.com/images/I/81ftdI4AaaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81uLAFiPU3L._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/815fEEpokvL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/81oI7WF0mNL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71njuJyUmLL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/91pGuMulLeL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "10.5", quantity: 12 },
          { size: "13", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Sole material Polyurethane",
      "Shaft height Ankle",
      "Outer material Canvas",
      "Inner material Synthetic",
    ],
    features: ["The super versatile trail running shoe for all uses"],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 92,
  },
  {
    id: uuidv4().toString().replace(/-/g, ""),
    gender: "men",
    sport: "hiking",
    brand: "salomon",
    name: "elixir active gtx",
    price: 155,
    aivalableColors: ["black"],
    sizes: [
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "12.5",
      "13",
    ],
    colors: [
      {
        id: uuidv4().toString().replace(/-/g, ""),
        color: "black",
        images: [
          "https://m.media-amazon.com/images/I/61FzDysiHUL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/71mb2Bl8PaL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61xsloS+CfL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/51h6HgP2VwL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61OXIkq3CGL._AC_SY695_.jpg",
          "https://m.media-amazon.com/images/I/61ja61zwrmL._AC_SY695_.jpg",
        ],
        sizes: [
          { size: "7", quantity: 12 },
          { size: "7.5", quantity: 12 },
          { size: "8", quantity: 12 },
          { size: "8.5", quantity: 12 },
          { size: "9", quantity: 12 },
          { size: "9.5", quantity: 12 },
          { size: "10", quantity: 12 },
          { size: "10.5", quantity: 12 },
          { size: "11", quantity: 12 },
          { size: "11.5", quantity: 12 },
          { size: "12", quantity: 12 },
          { size: "12.5", quantity: 12 },
          { size: "13", quantity: 5 },
        ],
      },
    ],
    reviews: [
      {
        userId: "user1",
        displayName: "John Doe",
        reviewText: "Super comfortable and durable. Perfect for long runs!",
        rating: 5,
        date: "2024-12-15",
      },
      {
        userId: "user2",
        displayName: "John Doe",
        reviewText: "Great grip and fit, but the color fades slightly.",
        rating: 4,
        date: "2024-12-10",
      },
    ],
    details: [
      "Sole material Polyurethane",
      "Shaft height Ankle",
      "Outer material Canvas",
      "Inner material Synthetic",
    ],
    features: ["The super versatile trail running shoe for all uses"],
    realeaseDate: "02-01-2025",
    isFeatured: true,
    isOnsale: false,
    salePrice: 112,
  },
];
